package BillingForm;


import LogIn.LoginForm;
import PharmacistLogin.PhamacistLogin;
import ProductForm.ProductForm;
import static ProductForm.ProductForm.convertUtilDateToSqlDate;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import orderForm.OrderForm;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public final class BillingForm extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pat = null;
    /**
     * Creates new form BillingForm
     */
    public BillingForm() {
       initComponents(); 
        setSize(1920,1080);
       setLocation(0,0);
        setResizable(false);
        loadcombo();
        
          jPanel2.setVisible(false);
        closenavi_btn.setVisible(false);
        gohome_btn.setVisible(false);
        goproduct_btn.setVisible(false);
        goorder_btn.setVisible(true);
        gobilling_btn.setVisible(false);
        signout_btn.setVisible(false);
        open_navi_btn.setVisible(true);

          try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql1 ="SELECT bp.bid,bp.pid,bp.quantity,b.date,b.total,p.name,p.category,p.amount FROM bill_products bp Left Outer Join bill b ON bp.bid = b.bid Left Outer Join product p ON bp.pid = p.pid Group By bp.bid";
            pat = con.prepareStatement(sql1);
            rs=pat.executeQuery();
            bill1_table.setModel(DbUtils.resultSetToTableModel(rs));
            int no = bill1_table.getRowCount();
            no = no+1;
            jTextField3.setText("" + no);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }

    public void loadcombo(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           String sql = "SELECT username FROM pharmacist";
           pat = con.prepareStatement(sql);
           rs = pat.executeQuery();
           while(rs.next()){
               pharmacist_combo.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        gohome_btn = new javax.swing.JButton();
        closenavi_btn = new javax.swing.JButton();
        goproduct_btn = new javax.swing.JButton();
        goorder_btn = new javax.swing.JButton();
        gobilling_btn = new javax.swing.JButton();
        signout_btn = new javax.swing.JButton();
        label13 = new java.awt.Label();
        label18 = new java.awt.Label();
        label14 = new java.awt.Label();
        jTextField3 = new javax.swing.JTextField();
        label15 = new java.awt.Label();
        label7 = new java.awt.Label();
        searchproduct_txt = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        view_txt = new javax.swing.JTextArea();
        search_btn = new javax.swing.JButton();
        label16 = new java.awt.Label();
        searchbill_txt = new javax.swing.JTextField();
        quantity_btn = new javax.swing.JSpinner();
        searchbill_btn = new javax.swing.JButton();
        label10 = new java.awt.Label();
        print_btn = new javax.swing.JButton();
        addproduct_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        total_txt = new javax.swing.JTextField();
        allbillbtn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        view_btn = new javax.swing.JButton();
        pharmacist_combo = new javax.swing.JComboBox<String>();
        label8 = new java.awt.Label();
        label17 = new java.awt.Label();
        jLabel8 = new javax.swing.JLabel();
        reset_btn = new javax.swing.JButton();
        addbill_btn = new javax.swing.JButton();
        label9 = new java.awt.Label();
        jScrollPane4 = new javax.swing.JScrollPane();
        billproduct_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill1_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        billdatechooser = new com.toedter.calendar.JDateChooser();
        open_navi_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 102, 0));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("HAPPY SMILE DENTAL CLINIC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(832, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 70);

        jPanel2.setBackground(new java.awt.Color(102, 153, 0));

        gohome_btn.setText("HOME");
        gohome_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gohome_btnActionPerformed(evt);
            }
        });

        closenavi_btn.setBackground(new java.awt.Color(204, 204, 204));
        closenavi_btn.setForeground(new java.awt.Color(0, 102, 0));
        closenavi_btn.setText("||||");
        closenavi_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        closenavi_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closenavi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closenavi_btnActionPerformed(evt);
            }
        });

        goproduct_btn.setText("PRODUCTS ");
        goproduct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goproduct_btnActionPerformed(evt);
            }
        });

        goorder_btn.setText("ORDERS");
        goorder_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goorder_btnActionPerformed(evt);
            }
        });

        gobilling_btn.setText("BILLING");
        gobilling_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobilling_btnActionPerformed(evt);
            }
        });

        signout_btn.setText("SIGN OUT");
        signout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gohome_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(goproduct_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(goorder_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gobilling_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(signout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closenavi_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closenavi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gohome_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(goproduct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(goorder_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gobilling_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(701, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 270, 1010);

        label13.setAlignment(java.awt.Label.CENTER);
        label13.setBackground(new java.awt.Color(0, 102, 0));
        label13.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        label13.setForeground(new java.awt.Color(255, 255, 255));
        label13.setText("Date");
        getContentPane().add(label13);
        label13.setBounds(70, 420, 160, 30);

        label18.setAlignment(java.awt.Label.CENTER);
        label18.setBackground(new java.awt.Color(0, 102, 0));
        label18.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        label18.setForeground(new java.awt.Color(255, 255, 255));
        label18.setText("Total");
        getContentPane().add(label18);
        label18.setBounds(70, 370, 160, 30);

        label14.setAlignment(java.awt.Label.CENTER);
        label14.setBackground(new java.awt.Color(0, 102, 0));
        label14.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        label14.setForeground(new java.awt.Color(255, 255, 255));
        label14.setText("Bill number");
        getContentPane().add(label14);
        label14.setBounds(60, 140, 170, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(250, 140, 190, 30);

        label15.setAlignment(java.awt.Label.CENTER);
        label15.setBackground(new java.awt.Color(0, 102, 0));
        label15.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        label15.setForeground(new java.awt.Color(255, 255, 255));
        label15.setText("Products");
        getContentPane().add(label15);
        label15.setBounds(60, 180, 170, 30);

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(new java.awt.Color(0, 102, 51));
        label7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("ADD PRODUCTS FOR BILL");
        getContentPane().add(label7);
        label7.setBounds(280, 580, 320, 50);

        searchproduct_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchproduct_txtActionPerformed(evt);
            }
        });
        getContentPane().add(searchproduct_txt);
        searchproduct_txt.setBounds(80, 680, 600, 30);

        view_txt.setColumns(20);
        view_txt.setRows(5);
        jScrollPane8.setViewportView(view_txt);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(920, 670, 970, 270);

        search_btn.setBackground(new java.awt.Color(51, 102, 0));
        search_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        search_btn.setForeground(new java.awt.Color(204, 255, 204));
        search_btn.setText("SEARCH");
        search_btn.setBorder(null);
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn);
        search_btn.setBounds(690, 680, 120, 40);

        label16.setAlignment(java.awt.Label.CENTER);
        label16.setBackground(new java.awt.Color(0, 102, 0));
        label16.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        label16.setForeground(new java.awt.Color(255, 255, 255));
        label16.setText("Quantity");
        getContentPane().add(label16);
        label16.setBounds(90, 900, 190, 30);

        searchbill_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbill_txtActionPerformed(evt);
            }
        });
        getContentPane().add(searchbill_txt);
        searchbill_txt.setBounds(960, 150, 570, 40);

        quantity_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        quantity_btn.setValue(1);
        getContentPane().add(quantity_btn);
        quantity_btn.setBounds(300, 900, 140, 30);

        searchbill_btn.setBackground(new java.awt.Color(51, 102, 0));
        searchbill_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        searchbill_btn.setForeground(new java.awt.Color(204, 255, 204));
        searchbill_btn.setText("SEARCH");
        searchbill_btn.setBorder(null);
        searchbill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbill_btnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbill_btn);
        searchbill_btn.setBounds(1550, 150, 100, 40);

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setBackground(new java.awt.Color(0, 102, 51));
        label10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("SEARCH FOR BILL");
        getContentPane().add(label10);
        label10.setBounds(1260, 80, 290, 50);

        print_btn.setBackground(new java.awt.Color(51, 102, 0));
        print_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        print_btn.setForeground(new java.awt.Color(204, 255, 204));
        print_btn.setText("GENERATE REPORT");
        print_btn.setActionCommand("CLEAR");
        print_btn.setBorder(null);
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });
        getContentPane().add(print_btn);
        print_btn.setBounds(1730, 970, 160, 40);

        addproduct_btn.setBackground(new java.awt.Color(51, 102, 0));
        addproduct_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        addproduct_btn.setForeground(new java.awt.Color(204, 255, 204));
        addproduct_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ad2.png"))); // NOI18N
        addproduct_btn.setText("ADD");
        addproduct_btn.setBorder(null);
        addproduct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproduct_btnActionPerformed(evt);
            }
        });
        getContentPane().add(addproduct_btn);
        addproduct_btn.setBounds(660, 960, 170, 40);

        clear_btn.setBackground(new java.awt.Color(51, 102, 0));
        clear_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(204, 255, 204));
        clear_btn.setText("CLEAR");
        clear_btn.setBorder(null);
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn);
        clear_btn.setBounds(460, 960, 180, 40);

        total_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_txtActionPerformed(evt);
            }
        });
        total_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total_txtKeyTyped(evt);
            }
        });
        getContentPane().add(total_txt);
        total_txt.setBounds(260, 370, 180, 30);

        allbillbtn.setBackground(new java.awt.Color(51, 102, 0));
        allbillbtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        allbillbtn.setForeground(new java.awt.Color(204, 255, 204));
        allbillbtn.setText("VIEW ALL BILLS");
        allbillbtn.setBorder(null);
        allbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allbillbtnActionPerformed(evt);
            }
        });
        getContentPane().add(allbillbtn);
        allbillbtn.setBounds(1680, 150, 190, 40);

        delete_btn.setBackground(new java.awt.Color(51, 102, 0));
        delete_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(204, 255, 204));
        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        delete_btn.setText("DELETE");
        delete_btn.setActionCommand("CLEAR");
        delete_btn.setBorder(null);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn);
        delete_btn.setBounds(1550, 970, 160, 40);

        view_btn.setBackground(new java.awt.Color(51, 102, 0));
        view_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        view_btn.setForeground(new java.awt.Color(204, 255, 204));
        view_btn.setText("VIEW DETAILS");
        view_btn.setActionCommand("VIEW");
        view_btn.setBorder(null);
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });
        getContentPane().add(view_btn);
        view_btn.setBounds(1710, 470, 170, 40);

        getContentPane().add(pharmacist_combo);
        pharmacist_combo.setBounds(650, 370, 170, 30);

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setBackground(new java.awt.Color(0, 102, 51));
        label8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("VIEW BILL DETAILS");
        getContentPane().add(label8);
        label8.setBounds(1260, 590, 280, 50);

        label17.setAlignment(java.awt.Label.CENTER);
        label17.setBackground(new java.awt.Color(0, 102, 0));
        label17.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        label17.setForeground(new java.awt.Color(255, 255, 255));
        label17.setText("Billed By");
        getContentPane().add(label17);
        label17.setBounds(490, 370, 150, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0), new java.awt.Color(102, 204, 0), new java.awt.Color(51, 153, 0)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(860, 550, 1060, 530);

        reset_btn.setBackground(new java.awt.Color(51, 102, 0));
        reset_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(204, 255, 204));
        reset_btn.setText("RESET");
        reset_btn.setBorder(null);
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reset_btn);
        reset_btn.setBounds(490, 470, 150, 40);

        addbill_btn.setBackground(new java.awt.Color(51, 102, 0));
        addbill_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        addbill_btn.setForeground(new java.awt.Color(204, 255, 204));
        addbill_btn.setText("GENERATE BILL");
        addbill_btn.setBorder(null);
        addbill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbill_btnActionPerformed(evt);
            }
        });
        getContentPane().add(addbill_btn);
        addbill_btn.setBounds(660, 470, 160, 40);

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setBackground(new java.awt.Color(0, 102, 51));
        label9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("ADD NEW BILL");
        getContentPane().add(label9);
        label9.setBounds(260, 80, 370, 40);

        billproduct_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product id", "Product Name", "Amount", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(billproduct_table);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(60, 220, 760, 130);

        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(product_table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 740, 740, 140);

        bill1_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bill1_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(960, 210, 920, 210);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 153, 51), new java.awt.Color(51, 153, 0), new java.awt.Color(0, 153, 102), new java.awt.Color(0, 204, 51)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(860, 70, 1060, 480);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1490, 70, 430, 480);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0), new java.awt.Color(102, 204, 0), new java.awt.Color(51, 153, 0)));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 560, 860, 530);
        getContentPane().add(billdatechooser);
        billdatechooser.setBounds(260, 420, 180, 30);

        open_navi_btn.setBackground(new java.awt.Color(0, 102, 0));
        open_navi_btn.setForeground(new java.awt.Color(0, 102, 51));
        open_navi_btn.setText("||||");
        open_navi_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        open_navi_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        open_navi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_navi_btnActionPerformed(evt);
            }
        });
        getContentPane().add(open_navi_btn);
        open_navi_btn.setBounds(10, 80, 30, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0), new java.awt.Color(51, 204, 0), new java.awt.Color(51, 153, 0)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 70, 860, 480);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1510, 550, 410, 530);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(650, 550, 210, 530);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 70, 210, 480);

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
             try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql2 = "SELECT * FROM product WHERE name LIKE '"+searchproduct_txt.getText()+"%'";
            pat = con.prepareStatement(sql2);
            rs=pat.executeQuery();
            product_table.setModel(DbUtils.resultSetToTableModel(rs));
            searchproduct_txt.setText(null);
             if(product_table.getModel().getRowCount()<=0)
                    JOptionPane.showMessageDialog(null,"The Name you have entered is NOT available");
            searchproduct_txt.setText(null);
             }
                 catch(HeadlessException | SQLException ex){
                     JOptionPane.showMessageDialog(null, ex);
                 }
    }//GEN-LAST:event_search_btnActionPerformed

    private void searchproduct_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchproduct_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchproduct_txtActionPerformed

    private void searchbill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbill_btnActionPerformed
        // TODO add your handling code here:
         if(!searchbill_txt.getText().isEmpty()){
                try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql2 = "SELECT bp.bid,bp.pid,bp.quantity,b.date,b.total,p.name,p.category,p.amount FROM bill_products bp Left Outer Join bill b ON bp.bid = b.bid Left Outer Join product p ON bp.pid = p.pid WHERE bp.bid = ? Group By bp.bid";
            pat = con.prepareStatement(sql2);
            pat.setString(1,searchbill_txt.getText());
            rs=pat.executeQuery();
            bill1_table.setModel(DbUtils.resultSetToTableModel(rs));
            searchbill_txt.setText(null);
                if(product_table.getModel().getRowCount()<=0)
                    JOptionPane.showMessageDialog(null,"The Id you have entered is NOT available");
                }
                 catch(HeadlessException | SQLException ex){
                     JOptionPane.showMessageDialog(null, ex);
                 }
           }
      else
         JOptionPane.showMessageDialog(null,"PLEASE SPECIFY THE BILL ID TO SEARCH");
    }//GEN-LAST:event_searchbill_btnActionPerformed

       public void total(){
         float tot = 0;
         for(int i=0; i<billproduct_table.getRowCount();i++){
           float amount = Float.parseFloat((String)billproduct_table.getValueAt(i, 2)) * Integer.parseInt((String)billproduct_table.getValueAt(i, 3));
           tot += amount;
         }
         total_txt.setText(Float.toString(tot));
    }
       
    private void addproduct_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproduct_btnActionPerformed
        // TODO add your handling code here:
        if(!product_table.getSelectionModel().isSelectionEmpty()){
         try{
           int i =  product_table.getSelectedRow();
           TableModel model = product_table.getModel();
            
           String x = model.getValueAt(i,0).toString();
           String y = model.getValueAt(i,1).toString();
           String z = model.getValueAt(i,8).toString();
           String t = quantity_btn.getValue().toString();
           
          int val = Integer.parseInt(model.getValueAt(i, 9).toString());
          int quantity = Integer.parseInt(quantity_btn.getValue().toString());
          int res = val-quantity;
          searchproduct_txt.setText(Integer.toString(res));
          
          
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
                String sq4 = "UPDATE product SET quantity=? WHERE pid=?";
                pat = con.prepareStatement(sq4);
                pat.setString(1,searchproduct_txt.getText());
                pat.setString(2,model.getValueAt(i, 0).toString());
                pat.executeUpdate();
            searchproduct_txt.setText(null);
             } catch (SQLException ex) {
                 Logger.getLogger(BillingForm.class.getName()).log(Level.SEVERE, null, ex);
             }
           
           String[] row = {x,y,z,t};
           
           DefaultTableModel mod1 = (DefaultTableModel) billproduct_table.getModel();
           mod1.addRow(row);
           clear();
           total();          
       }
       catch(UnsupportedOperationException ex){
           JOptionPane.showMessageDialog(null,ex);
       }
        }
        else
            JOptionPane.showMessageDialog(null,"NO PRODUCTS ARE SELECTED.");
    }//GEN-LAST:event_addproduct_btnActionPerformed

    private void total_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_txtActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) billproduct_table.getModel();
        model.setRowCount(0);
        java.util.Date date = null;
         billdatechooser.setDate(date);
        total_txt.setText(null);
    }//GEN-LAST:event_reset_btnActionPerformed

     public void clear(){
        DefaultTableModel model = (DefaultTableModel) product_table.getModel();
        model.setRowCount(0);
        quantity_btn.setValue(1);
    }
    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clear_btnActionPerformed

        public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
        if(date!=null){
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
        }
        return null;
    }
        
    private void addbill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbill_btnActionPerformed
           if(billproduct_table.getRowCount()==0)
          JOptionPane.showMessageDialog(null,"ADD PRODUCTS FOR BILL"); 
      else if(total_txt.getText()==null || billdatechooser.getDate() == null)
          JOptionPane.showMessageDialog(null,"MAKE SURE YOU FILLED ALL FIELDS"); 
      else{
        try{
           String sql = "INSERT INTO bill" + "(bid,total,date,pharmacist)" + "VALUES (?,?,?,?)";
           con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           pat = con.prepareStatement(sql);
           pat.setString(1,jTextField3.getText());
           pat.setString(4, (String) pharmacist_combo.getSelectedItem());
           pat.setString(2,total_txt.getText());
           pat.setDate(3,convertUtilDateToSqlDate(billdatechooser.getDate())); 
           pat.executeUpdate();
           
           String sql1 = "INSERT INTO bill_products" + "(bid,pid,quantity)" + "VALUES (?,?,?)";
           for(int i=0; i<billproduct_table.getRowCount();i++){
           con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           pat = con.prepareStatement(sql1);
           pat.setString(1,jTextField3.getText());
           pat.setString(2,billproduct_table.getValueAt(i,0).toString());
           pat.setString(3,billproduct_table.getValueAt(i,3).toString());
           pat.executeUpdate();
           }
        
           
        JOptionPane.showMessageDialog(null,"BILL ADDED SUCCESSFULLY");                    
        DefaultTableModel model = (DefaultTableModel) billproduct_table.getModel();
        model.setRowCount(0);
        java.util.Date date = null;
        billdatechooser.setDate(date);
        total_txt.setText(null);
        
        con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
        String sql3 ="SELECT bp.bid,bp.pid,bp.quantity,b.date,b.total,p.name,p.category,p.amount FROM bill_products bp Left Outer Join bill b ON bp.bid = b.bid Left Outer Join product p ON bp.pid = p.pid Group By bp.bid";
        pat = con.prepareStatement(sql3);
        rs=pat.executeQuery();
        bill1_table.setModel(DbUtils.resultSetToTableModel(rs));
        
            int no = bill1_table.getRowCount();
            no = no+1;
            total_txt.setText("" + no);
       }
       catch(UnsupportedOperationException | SQLException ex){
           JOptionPane.showMessageDialog(null,ex);
       }  
      }// TODO add your handling code here:
    }//GEN-LAST:event_addbill_btnActionPerformed

    private void allbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allbillbtnActionPerformed
        // TODO add your handling code here:
         try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql1 ="SELECT bp.bid,bp.pid,bp.quantity,b.date,b.total,p.name,p.category,p.amount FROM bill_products bp Left Outer Join bill b ON bp.bid = b.bid Left Outer Join product p ON bp.pid = p.pid Group By bp.bid";
            pat = con.prepareStatement(sql1);
            rs=pat.executeQuery();
            bill1_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_allbillbtnActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
          if(!bill1_table.getSelectionModel().isSelectionEmpty()){
        // TODO add your handling code here:
        try{
        int i = bill1_table.getSelectedRow();
        TableModel model = bill1_table.getModel();
        
        view_txt.setText("*******************HAPPY SMILE DENTAL CLINIC**********************\n");
        view_txt.setText(view_txt.getText()+"Bill ID : " + model.getValueAt(i, 0).toString()+"\n");
        view_txt.setText(view_txt.getText()+"Date : " + model.getValueAt(i, 3).toString()+"\n");
        view_txt.setText(view_txt.getText()+"Total : " + model.getValueAt(i, 4).toString()+"\n\n");
        
       con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
       String sql1 ="SELECT bp.bid,bp.pid,bp.quantity,b.date,b.total,p.name,p.category,p.amount FROM bill_products bp Left Outer Join bill b ON bp.bid = b.bid Left Outer Join product p ON bp.pid = p.pid WHERE bp.bid = ?";
       pat = con.prepareStatement(sql1);
       pat.setString(1, bill1_table.getValueAt(i, 0).toString());
       rs=pat.executeQuery();
       bill1_table.setModel(DbUtils.resultSetToTableModel(rs));
         
         TableModel m2 = bill1_table.getModel();
        for(int x=0;x<=m2.getRowCount();x++){
        view_txt.setText(view_txt.getText()+"Product id : " + m2.getValueAt(x, 1).toString()+"\n");
        view_txt.setText(view_txt.getText()+"Quantity : "  + m2.getValueAt(x, 2).toString()+"\n");
        view_txt.setText(view_txt.getText()+"Name : " + m2.getValueAt(x, 5).toString()+"\n");
        view_txt.setText(view_txt.getText()+"Category : " + m2.getValueAt(x, 6).toString()+"\n");
        view_txt.setText(view_txt.getText()+"Amount : " + m2.getValueAt(x, 7).toString()+"\n\n");
        }        

        }catch(SQLException ex){
            
        }
        }
        else
             JOptionPane.showMessageDialog(null, "NOTHING SPECIFIED TO VIEW");
    }//GEN-LAST:event_view_btnActionPerformed

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed
        // TODO add your handling code here:
             if(!view_txt.getText().isEmpty()){
        try {
            Boolean printdata = view_txt.print();
            
            if(printdata)
                JOptionPane.showMessageDialog(null,"Done Printing.");
        } catch (PrinterException ex) {
            Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else
            JOptionPane.showMessageDialog(null,"NOTHING SPECIFIED TO PRINT.");
    }//GEN-LAST:event_print_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
         if(!view_txt.getText().isEmpty()){
        // TODO add your handling code here:
       int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE?", "DELETE", JOptionPane.YES_NO_OPTION);
        if(op==0){
        try{
             TableModel model = bill1_table.getModel();
             con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
              String sql1 ="SELECT bp.bid,bp.pid,bp.quantity,b.date,b.total,p.name,p.category,p.amount FROM bill_products bp Left Outer Join bill b ON bp.bid = b.bid Left Outer Join product p ON bp.pid = p.pid WHERE bp.bid = ? GROUP BY bp.bid";
             pat = con.prepareStatement(sql1);
             pat.setString(1, model.getValueAt(0, 0).toString());
             rs=pat.executeQuery();
             bill1_table.setModel(DbUtils.resultSetToTableModel(rs));
             
          TableModel m1 = bill1_table.getModel();
        
            String sql3 = "DELETE FROM bill_products WHERE bid = ?";
            pat = con.prepareStatement(sql3);
            pat.setString(1, m1.getValueAt(0, 0).toString());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "BILL DELETED SUCCESSFULLY");
            
            DefaultTableModel model1= (DefaultTableModel) bill1_table.getModel();
            model1.setRowCount(0);
            view_txt.setText(null);
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        }
         }
        else
              JOptionPane.showMessageDialog(null, "NOTHING SPECIFIED TO DELETE");
    }//GEN-LAST:event_delete_btnActionPerformed

    private void open_navi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_navi_btnActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        closenavi_btn.setVisible(true);
        gohome_btn.setVisible(true);
        goproduct_btn.setVisible(true);
        goorder_btn.setVisible(true);
        gobilling_btn.setVisible(true);
        signout_btn.setVisible(true);
        open_navi_btn.setVisible(false);
    }//GEN-LAST:event_open_navi_btnActionPerformed

    private void gohome_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gohome_btnActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "CHANGE TO HOME PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            PhamacistLogin pl = new PhamacistLogin();
            pl.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_gohome_btnActionPerformed

    private void closenavi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closenavi_btnActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        closenavi_btn.setVisible(false);
        gohome_btn.setVisible(false);
        goproduct_btn.setVisible(false);
        goorder_btn.setVisible(false);
        gobilling_btn.setVisible(false);
        signout_btn.setVisible(false);
        open_navi_btn.setVisible(true);
    }//GEN-LAST:event_closenavi_btnActionPerformed

    private void goproduct_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goproduct_btnActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "CHANGE TO PRODUCT PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            ProductForm pl = new ProductForm();
            pl.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_goproduct_btnActionPerformed

    private void goorder_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goorder_btnActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "CHANGE TO ORDER PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            OrderForm ol = new OrderForm();
            ol.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_goorder_btnActionPerformed

    private void gobilling_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobilling_btnActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "YOU ARE ALREADY IN BILLING PAGE. DO YOU WANT TO RESET PAGE?", "PAGE RESET", JOptionPane.YES_NO_OPTION);
        if(op==0){
            BillingForm bl = new BillingForm();
            bl.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_gobilling_btnActionPerformed

    private void signout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signout_btnActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO SIGN OUT?", "SIGN OUT", JOptionPane.YES_NO_OPTION);
        if(op==0){
            LoginForm l1 = new LoginForm();
            l1.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_signout_btnActionPerformed

    private void total_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_txtKeyTyped
         char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Total should be numeric value");

        } 
    }//GEN-LAST:event_total_txtKeyTyped

    private void searchbill_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbill_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbill_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbill_btn;
    private javax.swing.JButton addproduct_btn;
    private javax.swing.JButton allbillbtn;
    private javax.swing.JTable bill1_table;
    private com.toedter.calendar.JDateChooser billdatechooser;
    private javax.swing.JTable billproduct_table;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton closenavi_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton gobilling_btn;
    private javax.swing.JButton gohome_btn;
    private javax.swing.JButton goorder_btn;
    private javax.swing.JButton goproduct_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField3;
    private java.awt.Label label10;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label3;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JButton open_navi_btn;
    private javax.swing.JComboBox<String> pharmacist_combo;
    private javax.swing.JButton print_btn;
    private javax.swing.JTable product_table;
    private javax.swing.JSpinner quantity_btn;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton searchbill_btn;
    private javax.swing.JTextField searchbill_txt;
    private javax.swing.JTextField searchproduct_txt;
    private javax.swing.JButton signout_btn;
    private javax.swing.JTextField total_txt;
    private javax.swing.JButton view_btn;
    private javax.swing.JTextArea view_txt;
    // End of variables declaration//GEN-END:variables
}
