/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chanelling;

import Reception.Receptionist_page;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Sujeeban
 */
public class Chanelling extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;    
    
    
    public Chanelling() {
        initComponents();
        setSize(1370,750);
        setResizable(false);
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableView = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        docName = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        View = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        Search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jPanel1 = new javax.swing.JPanel();
        Pdate = new com.toedter.calendar.JDateChooser();
        PNO = new javax.swing.JTextField();
        Pname = new javax.swing.JTextField();
        PID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ptime = new com.github.lgooddatepicker.components.TimePicker();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 620, 130, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(790, 670, 130, 31);

        add.setBackground(new java.awt.Color(102, 255, 102));
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(30, 620, 110, 31);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        TableView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableView);
        if (TableView.getColumnModel().getColumnCount() > 0) {
            TableView.getColumnModel().getColumn(3).setHeaderValue("Title 4");
            TableView.getColumnModel().getColumn(4).setHeaderValue("Title 5");
            TableView.getColumnModel().getColumn(5).setHeaderValue("Title 6");
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(790, 234, 659, 130);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Happy Smile Dental Clinic");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1520, 117);

        jLabel9.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel9.setText("Chennling Management");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(600, 130, 308, 39);

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 620, 130, 31);

        docName.setBackground(new java.awt.Color(51, 255, 255));
        docName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        docName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dr.Jeya", "Dr.Kamal", "Dr.Shaaru", "Dr.Suresh", "Dr.Thilini" }));
        docName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(docName);
        docName.setBounds(37, 256, 159, 44);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1306, 124, 82, 35);

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 620, 110, 31);

        jButton5.setBackground(new java.awt.Color(102, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton5.setText("Log out");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jButton5);
        jButton5.setBounds(1370, 130, 90, 35);

        View.setColumns(20);
        View.setRows(5);
        jScrollPane2.setViewportView(View);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(790, 411, 659, 240);

        jButton6.setText("jButton6");
        getContentPane().add(jButton6);
        jButton6.setBounds(1340, 670, 95, 30);

        search.setBackground(new java.awt.Color(102, 255, 102));
        search.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(1310, 190, 100, 30);

        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(1170, 190, 110, 30);

        jLabel3.setText("Search by");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(890, 190, 100, 30);

        jComboBox2.setBackground(new java.awt.Color(204, 255, 204));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "NAME", "DOCTOR NAME" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(1000, 190, 143, 30);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        PNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PNOKeyTyped(evt);
            }
        });

        Pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnameActionPerformed(evt);
            }
        });

        PID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Appointment ID");

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("Phone No");

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setText("Date");

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pdate, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(PNO, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(Pname, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(PID, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(Ptime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Ptime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(220, 230, 530, 350);

        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(0, 120, 80, 30);

        setSize(new java.awt.Dimension(1491, 840));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
          if(Pname.getText().isEmpty()||PNO.getText().isEmpty()||Pdate.getDate()==null||Ptime.getTime()==(null)){
               JOptionPane.showMessageDialog(null, "Fields cannot be Empty");
          }
          else{
               
        try {
           String sql = "INSERT INTO chanelling(Pname,DR_Name,PNO,Pdate,Ptime) VALUES (?,?,?,?,?)";
           
           con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           pst = con.prepareStatement(sql);
           pst.setString(1,Pname.getText());
           pst.setString(2, docName.getSelectedItem().toString());
           
           pst.setString(3,PNO.getText());
           pst.setString(4,Pdate.getDate().toString());
           pst.setString(5,Ptime.getTime().toString());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "inserted Sucessfully");
       }
       
       catch(HeadlessException | SQLException ex ){
           JOptionPane.showMessageDialog(null, ex);
       }
        
       
          
          showTable(); 
          }
             
    }//GEN-LAST:event_addActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            clearfield();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        
         if(PID.getText().isEmpty()){
            
             JOptionPane.showMessageDialog(null, "Enter Pid to Delete ");
        }       
         else{
        
        int YesOrNo =  JOptionPane.showConfirmDialog(null,"do you want to Delete?","",JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0){
        
        
        try {
           String sql = "DELETE FROM chanelling WHERE PID = ?";
         con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           pst = con.prepareStatement(sql);
           pst.setString(1,PID.getText());
            pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Delete Sucessfully");
       }
       
       catch(HeadlessException | SQLException ex ){
           JOptionPane.showMessageDialog(null, ex);
       }
         showTable();
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

         if(PID.getText().isEmpty()){
            
             JOptionPane.showMessageDialog(null, "Enter Pid to Update ");
        }       
    
        
        int YesOrNo =  JOptionPane.showConfirmDialog(null,"do you want to Update?","",JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0){
        
        
        try {
           String sql = "UPDATE chanelling SET Pname=?,PNO=?,Pdate=?,Ptime= ? WHERE pid = ?";
        con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           pst = con.prepareStatement(sql);
           pst.setString(1,Pname.getText());
           pst.setString(2,PNO.getText());
           pst.setString(3,Pdate.getDate().toString());
           pst.setString(4,Ptime.getTime().toString());
           pst.setString(5,PID.getText().toString());
           
           pst.executeUpdate();
           
           
       }
       
       catch(HeadlessException | SQLException ex ){
           JOptionPane.showMessageDialog(null, ex);
       }
         showTable();                               
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void PIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIDActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        
    }//GEN-LAST:event_SearchActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        Object sel1 = jComboBox2.getSelectedItem();
                String selitem = sel1.toString();
            
           if("ID" == selitem){
                try{
          con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql2 = "SELECT * FROM chanelling WHERE PID = ?";
            pst = con.prepareStatement(sql2);
            pst.setString(1,Search.getText());
            rs=pst.executeQuery();
            TableView.setModel(DbUtils.resultSetToTableModel(rs));
            
                if(TableView.getModel().getRowCount()<=0)
                    JOptionPane.showMessageDialog(null,"Please enter the correct ID");
                }
                 catch(Exception ex){
                     JOptionPane.showMessageDialog(null, ex);
                 }
           }
           else if("NAME" == selitem){
                try{
          con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql3 = "SELECT * FROM chanelling WHERE Pname LIKE '"+Search.getText()+"%'";
            pst = con.prepareStatement(sql3);
            rs=pst.executeQuery();
            TableView.setModel(DbUtils.resultSetToTableModel(rs));
             if(TableView.getModel().getRowCount()<=0)
                    JOptionPane.showMessageDialog(null,"Please Enter the correct Name");
                }
                 catch(Exception ex){
                     JOptionPane.showMessageDialog(null, ex);
                 }     
           }
           
          else if("DOCTOR NAME" == selitem){
                try{
         con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql3 = "SELECT * FROM chanelling WHERE DR_Name LIKE '"+Search.getText()+"%'";
            pst = con.prepareStatement(sql3);
            rs=pst.executeQuery();
            TableView.setModel(DbUtils.resultSetToTableModel(rs));
             if(TableView.getModel().getRowCount()<=0)
                    JOptionPane.showMessageDialog(null,"Please Enter the correct Name");
                }
                 catch(Exception ex){
    
                    JOptionPane.showMessageDialog(null, ex);
                 }}
    }//GEN-LAST:event_searchActionPerformed

    private void PnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnameActionPerformed

    private void PNOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PNOKeyTyped
       char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Phone number should be numeric value");

        }
    }//GEN-LAST:event_PNOKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try{
        int i = TableView.getSelectedRow();
        TableModel model = TableView.getModel();
        
        View.setText("*******************************************PATIENT Appointment***************************************\n");
        View.setText(View.getText()+"Appoinment ID : " + model.getValueAt(i, 0).toString()+"\n");
        View.setText(View.getText()+"Name : " + model.getValueAt(i, 1).toString()+"\n");
        View.setText(View.getText()+"Doctor Name : " + model.getValueAt(i, 2).toString()+"\n");
        View.setText(View.getText()+"Phone No : " + model.getValueAt(i, 3).toString()+"\n");
        View.setText(View.getText()+"Appoinment Date : "  + model.getValueAt(i, 4).toString()+"\n");
        View.setText(View.getText()+"Appoinment Time : " + model.getValueAt(i, 5).toString()+"\n");
     
        
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TableViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableViewMouseClicked
  /*int i = TableView.getSelectedRow();
       TableModel model = TableView.getModel();
      
       Pname.setText(model.getValueAt(i,1).toString());
       PNO.setText(model.getValueAt(i,1).toString()); 
       Pdate.setDate(model.getValueAt(i,1).toString()); */ 
    }//GEN-LAST:event_TableViewMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Receptionist_page obj = new Receptionist_page();
        obj.setVisible(true);
        dispose();
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

       
        
  public void showTable(){
  try{
        con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
        String sql = "SELECT * FROM chanelling ";
        pst = con.prepareStatement(sql);
        rs= pst.executeQuery();
        TableView.setModel((DbUtils.resultSetToTableModel(rs)));
  }
         catch(HeadlessException | SQLException ex ){
           JOptionPane.showMessageDialog(null, ex);
  
  
  }
  }
  public void clearfield(){
      Pname.setText(null);
     PNO.setText(null);
     Pdate.setDate(null);
     Ptime.setTime(null);
     PID.setText(null);
     
      
  }
  
   
    
        
    
    
        
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chanelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chanelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chanelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chanelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chanelling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PID;
    private javax.swing.JTextField PNO;
    private com.toedter.calendar.JDateChooser Pdate;
    private javax.swing.JTextField Pname;
    private com.github.lgooddatepicker.components.TimePicker Ptime;
    private javax.swing.JTextField Search;
    private javax.swing.JTable TableView;
    private javax.swing.JTextArea View;
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> docName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables

    private static class PID {

        public PID() {
        }
    }
}
