/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finance;


import LogIn.LoginForm;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author ADMIN
 */
public class EXPENSE extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public EXPENSE() {
        initComponents();
        setSize(1370,750);
        setResizable(false);
        showTableData(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        MEDI_COST = new javax.swing.JTextField();
        EMP_SAL = new javax.swing.JTextField();
        MAINTANENCE = new javax.swing.JTextField();
        BILL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        SUM_1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DATE = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        TRANS_NO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DESCRIPTION = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        SUM_2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        AMOUNT = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        jLabel1.setText("EXPENSE DETAILS");

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1123, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );

        jPanel2.setLayout(null);

        jButton17.setText("ANALISE");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17);
        jButton17.setBounds(22, 182, 81, 25);

        MEDI_COST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEDI_COSTActionPerformed(evt);
            }
        });
        MEDI_COST.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MEDI_COSTKeyTyped(evt);
            }
        });
        jPanel2.add(MEDI_COST);
        MEDI_COST.setBounds(105, 13, 131, 22);

        EMP_SAL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EMP_SALKeyTyped(evt);
            }
        });
        jPanel2.add(EMP_SAL);
        EMP_SAL.setBounds(85, 48, 138, 22);

        MAINTANENCE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MAINTANENCEKeyTyped(evt);
            }
        });
        jPanel2.add(MAINTANENCE);
        MAINTANENCE.setBounds(96, 88, 95, 22);

        BILL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BILLKeyTyped(evt);
            }
        });
        jPanel2.add(BILL);
        BILL.setBounds(144, 128, 126, 22);

        jLabel10.setText("MEDICINE COST");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 16, 93, 16);

        jLabel3.setText("EMP SALARY");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 51, 73, 16);

        jLabel4.setText("MAINTANENCE");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 91, 84, 16);

        jLabel5.setText("RENT & BILLS &OTHER");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 131, 132, 16);

        jButton7.setText("RESET");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(144, 182, 71, 25);

        jButton9.setText("VIEW");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(470, 130, 63, 25);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DATE", "AMOUNT"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(438, 23, 252, 92);

        jButton11.setText("ADD");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(590, 130, 57, 25);

        jLabel17.setText("TOTAL MEDICINE COST");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(438, 217, 136, 16);
        jPanel2.add(SUM_1);
        SUM_1.setBounds(586, 214, 134, 22);

        jLabel2.setText("MEDICINE COST");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(509, 0, 93, 16);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.jpg"))); // NOI18N
        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(60, 450, 120, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(60, 490, 120, 40);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\1111111111111111.png")); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(60, 530, 120, 40);

        jButton5.setText("<BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(1270, 590, 71, 25);

        jLabel6.setText("DATE");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(210, 430, 31, 16);
        jPanel2.add(DATE);
        DATE.setBounds(250, 430, 100, 22);

        jLabel7.setText("TRANS NO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(450, 430, 61, 16);

        TRANS_NO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TRANS_NOKeyTyped(evt);
            }
        });
        jPanel2.add(TRANS_NO);
        TRANS_NO.setBounds(530, 430, 92, 22);

        jLabel8.setText("DESCRIPTION");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(690, 430, 79, 16);

        DESCRIPTION.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "MEDICINE COST", "EMP SALARY", "MAINTANENCE", "RENT & BILLS" }));
        jPanel2.add(DESCRIPTION);
        DESCRIPTION.setBounds(780, 430, 120, 22);

        jButton8.setText("ADD");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(930, 130, 57, 25);

        jButton6.setText("VIEW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(800, 130, 63, 25);

        jLabel18.setText("TOTAL EMPLOYEE SALARY");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(770, 220, 152, 16);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DATE", "AMOUNT"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(760, 20, 268, 92);
        jPanel2.add(SUM_2);
        SUM_2.setBounds(940, 220, 132, 22);

        jLabel11.setText("EMP SALARY");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(824, 0, 73, 16);

        jButton15.setBackground(new java.awt.Color(0, 102, 51));
        jButton15.setText("LOG OUT");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);
        jButton15.setBounds(1260, 10, 90, 25);

        jLabel9.setText("AMOUNT");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(940, 430, 51, 16);

        AMOUNT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AMOUNTKeyTyped(evt);
            }
        });
        jPanel2.add(AMOUNT);
        AMOUNT.setBounds(1000, 430, 97, 22);

        jButton16.setText("RESET");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);
        jButton16.setBounds(1120, 430, 71, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DATE", "TRANS NO", "DESCRIPTION", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(207, 464, 966, 116);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, -10, 650, 700);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(648, -10, 650, 700);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(1300, -10, 90, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1404, 894));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql ="SELECT joindate , salary FROM user";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(INCOME.class.getName()).log(Level.SEVERE, null, ex);
        }      

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql ="SELECT date , total FROM phorder";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable5.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(INCOME.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(AMOUNT.getText().isEmpty()||DATE.getDate()==null||DESCRIPTION.getSelectedItem() == "SELECT"){
               JOptionPane.showMessageDialog(null, "Fields cannot be Empty");
             
               
          }
        else{
        try{
           String sql = "INSERT INTO expense" + "(DATE, DESCRIPTION, AMOUNT)" + "VALUES (?,?,?)";
           con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           pst = con.prepareStatement(sql);
           pst.setString(2,(String) DESCRIPTION.getSelectedItem());
           pst.setString(3,AMOUNT.getText());
           pst.setDate(1, convertUtilDateToSqlDate(DATE.getDate()));
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null,"Inserted Successfully");
           showTableData();
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);

        }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
           String sql = "UPDATE expense SET DATE= ?,DESCRIPTION=?,AMOUNT= ?  WHERE TRANS_NO = ?";
           con = DriverManager.getConnection("jdbc:mysql://localhost/HappySmile","root","");
           pst = con.prepareStatement(sql);
           pst.setString(2,(String) DESCRIPTION.getSelectedItem());
           pst.setString(3,AMOUNT.getText());
           pst.setDate(1, convertUtilDateToSqlDate(DATE.getDate()));
           pst.setString(4,TRANS_NO.getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null,"Updated Successfully");
           showTableData();
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
           String sql = "DELETE FROM expense WHERE TRANS_NO = ?";
           con = DriverManager.getConnection("jdbc:mysql://localhost/HappySmile","root","");
           pst = con.prepareStatement(sql);
          pst.setString(1, TRANS_NO.getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null,"Deleted Successfully");
           showTableData();
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);

        }       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO SIGN OUT?", "SIGN OUT", JOptionPane.YES_NO_OPTION);
        if(op==0){
            LoginForm l2 = new LoginForm();
            l2.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        FINANCE obj = new FINANCE();
        obj.setVisible(true);
        dispose();
        this.setVisible(false);
                
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        clearText1();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        clearText();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("MEDICINE COST", new Integer(MEDI_COST.getText()));
        pieDataset.setValue("EMPLOYEE SALARY", new Integer(EMP_SAL.getText()));
        pieDataset.setValue("MAINTANENCE", new Integer(MAINTANENCE.getText()));
        pieDataset.setValue("RENTS & BILLS",new Integer(BILL.getText()));

        JFreeChart chart = ChartFactory.createPieChart("EXPENSE", pieDataset,true,true,true);
        PiePlot p = (PiePlot)chart.getPlot();
        ChartFrame frame = new ChartFrame("EXPENSE",chart);
        frame.setVisible(true);
        frame.setSize(450,500);

    }//GEN-LAST:event_jButton17ActionPerformed

    private void MEDI_COSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEDI_COSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MEDI_COSTActionPerformed

    private void MEDI_COSTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MEDI_COSTKeyTyped
       char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Amount should be numeric value");

        } 
    }//GEN-LAST:event_MEDI_COSTKeyTyped

    private void EMP_SALKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EMP_SALKeyTyped
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Amount should be numeric value");

        } 
    }//GEN-LAST:event_EMP_SALKeyTyped

    private void MAINTANENCEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MAINTANENCEKeyTyped
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Amount should be numeric value");

        } 
    }//GEN-LAST:event_MAINTANENCEKeyTyped

    private void BILLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BILLKeyTyped
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Amount should be numeric value");

        } 
    }//GEN-LAST:event_BILLKeyTyped

    private void TRANS_NOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TRANS_NOKeyTyped
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Amount should be numeric value");

        } 
    }//GEN-LAST:event_TRANS_NOKeyTyped

    private void AMOUNTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AMOUNTKeyTyped
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Amount should be numeric value");

        } 
    }//GEN-LAST:event_AMOUNTKeyTyped
  
    private static Date convertUtilDateToSqlDate(java.util.Date date){
        if(date!=null){
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
    }
        return null;
    }
    public void showTableData(){
    
     try{    
    
        con = DriverManager.getConnection("jdbc:mysql://localhost/HappySmile","root","");
        String sql = "SELECT * FROM expense";
          pst = con.prepareStatement(sql);
          rs = pst.executeQuery();
          jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
      catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex);
    }
  }
   public void clearText1(){
    
        DATE.setDate(null);
        DESCRIPTION.setSelectedItem(null);
        AMOUNT.setText(null);
   }
   
   public void clearText(){
    
        MEDI_COST.setText(null);
        EMP_SAL.setText(null);
        MAINTANENCE.setText(null);
        BILL.setText(null);
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EXPENSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EXPENSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EXPENSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EXPENSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EXPENSE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AMOUNT;
    private javax.swing.JTextField BILL;
    private com.toedter.calendar.JDateChooser DATE;
    private javax.swing.JComboBox DESCRIPTION;
    private javax.swing.JTextField EMP_SAL;
    private javax.swing.JTextField MAINTANENCE;
    private javax.swing.JTextField MEDI_COST;
    private javax.swing.JTextField SUM_1;
    private javax.swing.JTextField SUM_2;
    private javax.swing.JTextField TRANS_NO;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
