package LogIn;


import Patient_History.PatientHistory;
import PharmacistLogin.PhamacistLogin;
import Reception.Receptionist_page;
import adminlogin.adminlogin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class LoginForm extends javax.swing.JFrame {
    String k;
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pat = null;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(800,539);
       // setLocation(650,250);
        setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jButton6 = new javax.swing.JButton();
        label5 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(0, 102, 0));
        label2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Password");
        getContentPane().add(label2);
        label2.setBounds(220, 340, 140, 30);

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 255, 204));
        jButton2.setText("PHARMACIST");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 180, 140, 50);

        jButton10.setBackground(new java.awt.Color(102, 102, 0));
        jButton10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 255, 204));
        jButton10.setText("PHARMACIST");
        jButton10.setBorder(null);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(630, 180, 140, 50);

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 255, 204));
        jButton3.setText("ADMINISTRATOR");
        jButton3.setBorder(null);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(80, 180, 150, 50);

        jButton7.setBackground(new java.awt.Color(102, 102, 0));
        jButton7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 255, 204));
        jButton7.setText("ADMINISTRATOR");
        jButton7.setBorder(null);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(80, 180, 150, 50);

        jButton4.setBackground(new java.awt.Color(0, 102, 0));
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 255, 204));
        jButton4.setText("DOCTOR");
        jButton4.setBorder(null);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 180, 160, 50);

        jButton8.setBackground(new java.awt.Color(102, 102, 0));
        jButton8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 255, 204));
        jButton8.setText("DOCTOR");
        jButton8.setBorder(null);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(260, 180, 160, 50);

        jButton5.setBackground(new java.awt.Color(0, 102, 0));
        jButton5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 255, 204));
        jButton5.setText("RECEPTIONIST");
        jButton5.setBorder(null);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(450, 180, 150, 50);

        jButton9.setBackground(new java.awt.Color(102, 102, 0));
        jButton9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 255, 204));
        jButton9.setText("RECEPTIONIST");
        jButton9.setBorder(null);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(450, 180, 150, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(390, 280, 190, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(390, 340, 190, 30);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 102, 0));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("HAPPY SMILE DENTAL CLINIC");
        getContentPane().add(label3);
        label3.setBounds(100, 0, 700, 70);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(0, 102, 0));
        label4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("User Name");
        getContentPane().add(label4);
        label4.setBounds(220, 280, 140, 30);

        jButton6.setBackground(new java.awt.Color(0, 102, 0));
        jButton6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 255, 153));
        jButton6.setText("SIGN IN");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setOpaque(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(330, 430, 170, 50);

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(new java.awt.Color(0, 102, 0));
        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("LOGIN AS");
        getContentPane().add(label5);
        label5.setBounds(20, 130, 150, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg5.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 153, 0), new java.awt.Color(0, 102, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        setBounds(0, 0, 818, 586);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
            jButton3.setEnabled(false);
            jButton3.setVisible(false);
            jButton7.setEnabled(true);
            jButton7.setVisible(true);
            jButton4.setEnabled(false);
            jButton4.setVisible(false);
            jButton5.setEnabled(false);
            jButton5.setVisible(false);
            jButton2.setEnabled(false);
            jButton2.setVisible(false);
            jButton8.setEnabled(false);
            jButton8.setVisible(false);
            jButton9.setEnabled(false);
            jButton9.setVisible(false);
            jButton10.setEnabled(false);
            jButton10.setVisible(false);
            
            jButton7.setText("ADMINISTRATOR");
            k = jButton7.getText();
            System.out.println(k);
                    
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
            jButton3.setEnabled(true);
            jButton3.setVisible(true);
            jButton7.setEnabled(false);
            jButton7.setVisible(false);
            jButton4.setEnabled(true);
            jButton4.setVisible(true);
            jButton5.setEnabled(true);
            jButton5.setVisible(true);
            jButton2.setEnabled(true);
            jButton2.setVisible(true);
             jButton8.setEnabled(false);
            jButton8.setVisible(false);
            jButton9.setEnabled(false);
            jButton9.setVisible(false);
            jButton10.setEnabled(false);
            jButton10.setVisible(false);
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
         jButton3.setEnabled(false);
            jButton3.setVisible(false);
            jButton7.setEnabled(false);
            jButton7.setVisible(false);
            jButton4.setEnabled(false);
            jButton4.setVisible(false);
            jButton5.setEnabled(false);
            jButton5.setVisible(false);
            jButton2.setEnabled(false);
            jButton2.setVisible(false);
            jButton8.setEnabled(true);
            jButton8.setVisible(true);
            jButton9.setEnabled(false);
            jButton9.setVisible(false);
            jButton10.setEnabled(false);
            jButton10.setVisible(false);
            
            jButton8.setText("DOCTOR");
            k = jButton8.getText();
            System.out.println(k);
                    
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
             jButton3.setEnabled(true);
            jButton3.setVisible(true);
            jButton7.setEnabled(false);
            jButton7.setVisible(false);
            jButton4.setEnabled(true);
            jButton4.setVisible(true);
            jButton5.setEnabled(true);
            jButton5.setVisible(true);
            jButton2.setEnabled(true);
            jButton2.setVisible(true);
             jButton8.setEnabled(false);
            jButton8.setVisible(false);
            jButton9.setEnabled(false);
            jButton9.setVisible(false);
            jButton10.setEnabled(false);
            jButton10.setVisible(false);

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
         jButton3.setEnabled(false);
            jButton3.setVisible(false);
            jButton7.setEnabled(false);
            jButton7.setVisible(false);
            jButton4.setEnabled(false);
            jButton4.setVisible(false);
            jButton5.setEnabled(false);
            jButton5.setVisible(false);
            jButton2.setEnabled(false);
            jButton2.setVisible(false);
            jButton8.setEnabled(false);
            jButton8.setVisible(false);
            jButton9.setEnabled(true);
            jButton9.setVisible(true);
            jButton10.setEnabled(false);
            jButton10.setVisible(false);
            
            jButton9.setText("RECEPTIONIST");
            k = jButton9.getText();
            System.out.println(k);
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        jButton3.setEnabled(true);
            jButton3.setVisible(true);
            jButton7.setEnabled(false);
            jButton7.setVisible(false);
            jButton4.setEnabled(true);
            jButton4.setVisible(true);
            jButton5.setEnabled(true);
            jButton5.setVisible(true);
            jButton2.setEnabled(true);
            jButton2.setVisible(true);
             jButton8.setEnabled(false);
            jButton8.setVisible(false);
            jButton9.setEnabled(false);
            jButton9.setVisible(false);
            jButton10.setEnabled(false);
            jButton10.setVisible(false);
            
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        jButton3.setEnabled(true);
            jButton3.setVisible(true);
            jButton7.setEnabled(false);
            jButton7.setVisible(false);
            jButton4.setEnabled(true);
            jButton4.setVisible(true);
            jButton5.setEnabled(true);
            jButton5.setVisible(true);
            jButton2.setEnabled(true);
            jButton2.setVisible(true);
             jButton8.setEnabled(false);
            jButton8.setVisible(false);
            jButton9.setEnabled(false);
            jButton9.setVisible(false);
            jButton10.setEnabled(false);
            jButton10.setVisible(false);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         jButton3.setEnabled(false);
            jButton3.setVisible(false);
            jButton7.setEnabled(false);
            jButton7.setVisible(false);
            jButton4.setEnabled(false);
            jButton4.setVisible(false);
            jButton5.setEnabled(false);
            jButton5.setVisible(false);
            jButton2.setEnabled(false);
            jButton2.setVisible(false);
            jButton8.setEnabled(false);
            jButton8.setVisible(false);
            jButton9.setEnabled(false);
            jButton9.setVisible(false);
            jButton10.setEnabled(true);
            jButton10.setVisible(true);
            
            jButton10.setText("PHARMACIST");
            k = jButton10.getText();
            System.out.println(k);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
         try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           
           // if(con==null){
            //    JOptionPane.showMessageDialog(this,"Connection Failed");
            //}
            String sql1 = "SELECT * FROM admin where username = '"+jTextField1.getText()+"' and password = '"+jPasswordField1.getText()+"'";
            String sql2 = "SELECT * FROM doctor where username = '"+jTextField1.getText()+"' and password = '"+jPasswordField1.getText()+"'";
            String sql3 = "SELECT * FROM receptionist where username = '"+jTextField1.getText()+"' and password = '"+jPasswordField1.getText()+"'";
            String sql4 = "SELECT * FROM pharmacist where username = '"+jTextField1.getText()+"' and password = '"+jPasswordField1.getText()+"'";
            if(null==k){
                JOptionPane.showMessageDialog(this, "SELECT YOUR USER TYPE");
            } 
            else if(jTextField1.getText().isEmpty() || jPasswordField1.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "USERNAME AND PASSWORD CANNOT BE EMPTY.");
            }
            else switch(k){
                case "ADMINISTRATOR":
                    try {
                       
                        pat = con.prepareStatement(sql1);
                        rs = pat.executeQuery();
                        
                        if(rs.next()){
                            System.out.println("ADMINISTRATOR");
                            adminlogin ph = new adminlogin();
                            ph.setVisible(true);
                            this.setVisible(false);
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "INCORRECT USERNAME OR PASSWORD");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                case "RECEPTIONIST":
                    try {
                       
                        pat = con.prepareStatement(sql3);
                        rs = pat.executeQuery();
                        
                        if(rs.next()){
                            System.out.println("RECEPTIONIST");
                            Receptionist_page ph = new Receptionist_page();
                            ph.setVisible(true);
                            this.setVisible(false);
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "INCORRECT USERNAME OR PASSWORD");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                case "PHARMACIST":
                    try {
                       
                        pat = con.prepareStatement(sql4);
                        rs = pat.executeQuery();
                        
                        if(rs.next()){
                            System.out.println("PHARMACIST");
                            PhamacistLogin pl = new PhamacistLogin();
                            pl.setVisible(true);
                            this.setVisible(false);
                        }
                       
                        else{
                            JOptionPane.showMessageDialog(this, "INCORRECT USERNAME OR PASSWORD");
                    
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                case "DOCTOR" :
                    try {
                       
                        pat = con.prepareStatement(sql2);
                        rs = pat.executeQuery();
                        
                        if(rs.next()){
                            System.out.println("DOCTOR");
                            PatientHistory ph = new PatientHistory();
                            ph.setVisible(true);
                            this.setVisible(false);
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "INCORRECT USERNAME OR PASSWORD");
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                    break;
                default :
                    break;
            }
        } catch (SQLException ex) {
           
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
