package ProductForm;


import PharmacistLogin.PhamacistLogin;
import orderForm.OrderForm;
import BillingForm.BillingForm;
import LogIn.LoginForm;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import static java.lang.Boolean.TRUE;
import java.sql.Connection;
import java.sql.Date;
import java.util.Calendar;
//import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class ProductForm extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pat = null;
    /**
     * Creates new form ProductForm
     */
    public ProductForm() {
        initComponents(); 
         setSize(1920,1080);
         setLocation(0,0);
        setResizable(false);
        navi_panel.setVisible(false);
        hide_navi_button.setVisible(false);
        go_home.setVisible(false);
        go_product.setVisible(false);
        go_order.setVisible(false);
        sign_out_btn.setVisible(false);
        go_billing.setVisible(false);
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        navi_panel = new javax.swing.JPanel();
        go_home = new javax.swing.JButton();
        hide_navi_button = new javax.swing.JButton();
        go_product = new javax.swing.JButton();
        go_order = new javax.swing.JButton();
        go_billing = new javax.swing.JButton();
        sign_out_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner1 = new javax.swing.JSpinner();
        label6 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        searchby_label = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        addamount_txt = new javax.swing.JTextField();
        comboselect = new javax.swing.JComboBox<String>();
        addname_txt = new javax.swing.JTextField();
        addspeci_txt = new javax.swing.JTextField();
        adddose_txt = new javax.swing.JTextField();
        reset_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        label23 = new java.awt.Label();
        Quantity = new java.awt.Label();
        label22 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label24 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        updatespeciality_txt = new javax.swing.JTextField();
        label21 = new java.awt.Label();
        updateamount_txt = new javax.swing.JTextField();
        category2_combo = new javax.swing.JComboBox<String>();
        updatename_txt = new javax.swing.JTextField();
        updatedose_txt = new javax.swing.JTextField();
        cancel_upd_btn = new javax.swing.JButton();
        update1_btn = new javax.swing.JButton();
        upmanuDateChooser = new com.toedter.calendar.JDateChooser();
        upcurrentDateChooser = new com.toedter.calendar.JDateChooser();
        upexpiryDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ManuDateChooser = new com.toedter.calendar.JDateChooser();
        expiryDateChooser = new com.toedter.calendar.JDateChooser();
        currentDateChooser = new com.toedter.calendar.JDateChooser();
        label13 = new java.awt.Label();
        category_combo = new javax.swing.JComboBox<String>();
        reset_button1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        print_btn = new javax.swing.JButton();
        label25 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        viedetail_txt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        clear_button = new javax.swing.JButton();
        viewall_button = new javax.swing.JButton();
        search_exp_button = new javax.swing.JButton();
        jButton_search = new javax.swing.JButton();
        textbox_search = new javax.swing.JTextField();
        view_button = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        search_table = new javax.swing.JTable();
        open_navi_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        navi_panel.setBackground(new java.awt.Color(102, 153, 0));

        go_home.setText("HOME");
        go_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_homeActionPerformed(evt);
            }
        });

        hide_navi_button.setBackground(new java.awt.Color(204, 204, 204));
        hide_navi_button.setForeground(new java.awt.Color(0, 102, 51));
        hide_navi_button.setText("||||");
        hide_navi_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        hide_navi_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hide_navi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hide_navi_buttonActionPerformed(evt);
            }
        });

        go_product.setText("PRODUCTS ");
        go_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_productActionPerformed(evt);
            }
        });

        go_order.setText("ORDERS");
        go_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_orderActionPerformed(evt);
            }
        });

        go_billing.setText("BILLING");
        go_billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_billingActionPerformed(evt);
            }
        });

        sign_out_btn.setText("SIGN OUT");
        sign_out_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_out_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navi_panelLayout = new javax.swing.GroupLayout(navi_panel);
        navi_panel.setLayout(navi_panelLayout);
        navi_panelLayout.setHorizontalGroup(
            navi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(go_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(go_product, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(go_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(go_billing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sign_out_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(navi_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hide_navi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navi_panelLayout.setVerticalGroup(
            navi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navi_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hide_navi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(go_home, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(go_product, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(go_order, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(go_billing, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sign_out_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(674, Short.MAX_VALUE))
        );

        getContentPane().add(navi_panel);
        navi_panel.setBounds(0, 80, 270, 1010);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 102, 0));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("HAPPY SMILE DENTAL CLINIC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(685, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 80);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(1230, 940, 220, 30);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(230, 930, 220, 30);

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(new java.awt.Color(0, 102, 0));
        label6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Quantity");
        getContentPane().add(label6);
        label6.setBounds(30, 930, 170, 30);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(0, 102, 0));
        label4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Amount");
        getContentPane().add(label4);
        label4.setBounds(30, 870, 170, 30);
        label4.getAccessibleContext().setAccessibleName("Expiry Date");

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(new java.awt.Color(0, 102, 51));
        label5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("ADD NEW PRODUCTS");
        getContentPane().add(label5);
        label5.setBounds(330, 570, 270, 50);

        searchby_label.setAlignment(java.awt.Label.CENTER);
        searchby_label.setBackground(new java.awt.Color(0, 102, 0));
        searchby_label.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        searchby_label.setForeground(new java.awt.Color(255, 255, 255));
        searchby_label.setText("SEARCH PRODUCT BY");
        getContentPane().add(searchby_label);
        searchby_label.setBounds(10, 170, 200, 30);

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(new java.awt.Color(0, 102, 0));
        label7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Category");
        getContentPane().add(label7);
        label7.setBounds(30, 730, 170, 30);

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setBackground(new java.awt.Color(0, 102, 0));
        label8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("Speciality");
        getContentPane().add(label8);
        label8.setBounds(500, 720, 180, 30);

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setBackground(new java.awt.Color(0, 102, 0));
        label9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("Dosage");
        getContentPane().add(label9);
        label9.setBounds(500, 650, 180, 30);

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setBackground(new java.awt.Color(0, 102, 0));
        label10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("Manufacture Date");
        getContentPane().add(label10);
        label10.setBounds(500, 800, 180, 30);

        label11.setAlignment(java.awt.Label.CENTER);
        label11.setBackground(new java.awt.Color(0, 102, 0));
        label11.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("Expiry Date");
        getContentPane().add(label11);
        label11.setBounds(30, 800, 170, 30);

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setBackground(new java.awt.Color(0, 102, 0));
        label12.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label12.setForeground(new java.awt.Color(255, 255, 255));
        label12.setText("Current Date");
        getContentPane().add(label12);
        label12.setBounds(500, 870, 180, 30);

        addamount_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addamount_txtKeyTyped(evt);
            }
        });
        getContentPane().add(addamount_txt);
        addamount_txt.setBounds(230, 870, 220, 30);

        comboselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "NAME", "CATEGORY", " " }));
        comboselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboselectActionPerformed(evt);
            }
        });
        getContentPane().add(comboselect);
        comboselect.setBounds(220, 170, 130, 30);

        addname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addname_txtActionPerformed(evt);
            }
        });
        addname_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addname_txtKeyPressed(evt);
            }
        });
        getContentPane().add(addname_txt);
        addname_txt.setBounds(230, 660, 220, 30);
        getContentPane().add(addspeci_txt);
        addspeci_txt.setBounds(700, 720, 220, 30);
        getContentPane().add(adddose_txt);
        adddose_txt.setBounds(700, 650, 220, 30);

        reset_button.setBackground(new java.awt.Color(51, 102, 0));
        reset_button.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        reset_button.setForeground(new java.awt.Color(204, 255, 204));
        reset_button.setText("RESET");
        reset_button.setBorder(null);
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(reset_button);
        reset_button.setBounds(650, 990, 150, 40);

        add_button.setBackground(new java.awt.Color(51, 102, 0));
        add_button.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        add_button.setForeground(new java.awt.Color(204, 255, 204));
        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ad2.png"))); // NOI18N
        add_button.setText("ADD");
        add_button.setBorder(null);
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(add_button);
        add_button.setBounds(810, 990, 140, 40);

        label23.setAlignment(java.awt.Label.CENTER);
        label23.setBackground(new java.awt.Color(0, 102, 0));
        label23.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label23.setForeground(new java.awt.Color(255, 255, 255));
        label23.setText("Amount");
        getContentPane().add(label23);
        label23.setBounds(1030, 870, 180, 30);

        Quantity.setAlignment(java.awt.Label.CENTER);
        Quantity.setBackground(new java.awt.Color(0, 102, 0));
        Quantity.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Quantity.setForeground(new java.awt.Color(255, 255, 255));
        Quantity.setText("Quantity");
        getContentPane().add(Quantity);
        Quantity.setBounds(1030, 940, 180, 30);

        label22.setAlignment(java.awt.Label.CENTER);
        label22.setBackground(new java.awt.Color(0, 102, 0));
        label22.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label22.setForeground(new java.awt.Color(255, 255, 255));
        label22.setText("Current Date");
        getContentPane().add(label22);
        label22.setBounds(1490, 870, 180, 30);

        label15.setAlignment(java.awt.Label.CENTER);
        label15.setBackground(new java.awt.Color(0, 102, 51));
        label15.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label15.setForeground(new java.awt.Color(255, 255, 255));
        label15.setText("SEARCH PRODUCTS");
        getContentPane().add(label15);
        label15.setBounds(330, 90, 300, 40);

        label16.setAlignment(java.awt.Label.CENTER);
        label16.setBackground(new java.awt.Color(0, 102, 0));
        label16.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label16.setForeground(new java.awt.Color(255, 255, 255));
        label16.setText("Product Name");
        getContentPane().add(label16);
        label16.setBounds(1030, 660, 180, 30);

        label17.setAlignment(java.awt.Label.CENTER);
        label17.setBackground(new java.awt.Color(0, 102, 0));
        label17.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label17.setForeground(new java.awt.Color(255, 255, 255));
        label17.setText("Category");
        getContentPane().add(label17);
        label17.setBounds(1030, 730, 180, 30);

        label24.setAlignment(java.awt.Label.CENTER);
        label24.setBackground(new java.awt.Color(0, 102, 51));
        label24.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label24.setForeground(new java.awt.Color(255, 255, 255));
        label24.setText("UPDATE PRODUCTS");
        getContentPane().add(label24);
        label24.setBounds(1330, 570, 270, 50);

        label18.setAlignment(java.awt.Label.CENTER);
        label18.setBackground(new java.awt.Color(0, 102, 0));
        label18.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label18.setForeground(new java.awt.Color(255, 255, 255));
        label18.setText("Speciality");
        getContentPane().add(label18);
        label18.setBounds(1490, 730, 180, 30);

        label19.setAlignment(java.awt.Label.CENTER);
        label19.setBackground(new java.awt.Color(0, 102, 0));
        label19.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label19.setForeground(new java.awt.Color(255, 255, 255));
        label19.setText("Dosage");
        getContentPane().add(label19);
        label19.setBounds(1490, 660, 180, 30);

        label20.setAlignment(java.awt.Label.CENTER);
        label20.setBackground(new java.awt.Color(0, 102, 0));
        label20.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label20.setForeground(new java.awt.Color(255, 255, 255));
        label20.setText("Manufacture Date");
        getContentPane().add(label20);
        label20.setBounds(1490, 800, 180, 30);
        getContentPane().add(updatespeciality_txt);
        updatespeciality_txt.setBounds(1690, 730, 210, 30);

        label21.setAlignment(java.awt.Label.CENTER);
        label21.setBackground(new java.awt.Color(0, 102, 0));
        label21.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label21.setForeground(new java.awt.Color(255, 255, 255));
        label21.setText("Expiry Date");
        getContentPane().add(label21);
        label21.setBounds(1030, 800, 180, 30);

        updateamount_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateamount_txtActionPerformed(evt);
            }
        });
        updateamount_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateamount_txtKeyTyped(evt);
            }
        });
        getContentPane().add(updateamount_txt);
        updateamount_txt.setBounds(1230, 870, 220, 30);

        category2_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stimulants", "Depressants", "Hillacinogens", "Dissociatives", "Opioids", "Inhalants", "Cannabis" }));
        getContentPane().add(category2_combo);
        category2_combo.setBounds(1230, 730, 220, 30);
        getContentPane().add(updatename_txt);
        updatename_txt.setBounds(1230, 660, 220, 30);

        updatedose_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedose_txtActionPerformed(evt);
            }
        });
        getContentPane().add(updatedose_txt);
        updatedose_txt.setBounds(1690, 660, 210, 30);

        cancel_upd_btn.setBackground(new java.awt.Color(51, 102, 0));
        cancel_upd_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        cancel_upd_btn.setForeground(new java.awt.Color(204, 255, 204));
        cancel_upd_btn.setText("CANCEL");
        cancel_upd_btn.setBorder(null);
        cancel_upd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_upd_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_upd_btn);
        cancel_upd_btn.setBounds(1600, 990, 150, 40);

        update1_btn.setBackground(new java.awt.Color(51, 102, 0));
        update1_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        update1_btn.setForeground(new java.awt.Color(204, 255, 204));
        update1_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        update1_btn.setText("UPDATE");
        update1_btn.setBorder(null);
        update1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update1_btn);
        update1_btn.setBounds(1770, 990, 130, 40);

        upmanuDateChooser.setDateFormatString("yyyy MM d");
        getContentPane().add(upmanuDateChooser);
        upmanuDateChooser.setBounds(1690, 800, 210, 30);

        upcurrentDateChooser.setDateFormatString("yyyy MM d");
        getContentPane().add(upcurrentDateChooser);
        upcurrentDateChooser.setBounds(1700, 870, 200, 30);

        upexpiryDateChooser.setDateFormatString("yyyy MM d");
        getContentPane().add(upexpiryDateChooser);
        upexpiryDateChooser.setBounds(1230, 800, 220, 30);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0), new java.awt.Color(51, 204, 0), new java.awt.Color(51, 153, 0)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(980, 550, 940, 530);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1630, 550, 290, 530);

        ManuDateChooser.setDateFormatString("yyyy MM d");
        ManuDateChooser.setPreferredSize(new java.awt.Dimension(27, 20));
        ManuDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ManuDateChooserPropertyChange(evt);
            }
        });
        getContentPane().add(ManuDateChooser);
        ManuDateChooser.setBounds(700, 800, 220, 30);

        expiryDateChooser.setDateFormatString("yyyy MM d");
        getContentPane().add(expiryDateChooser);
        expiryDateChooser.setBounds(230, 800, 220, 30);

        currentDateChooser.setDateFormatString("yyyy MM d");
        currentDateChooser.setPreferredSize(new java.awt.Dimension(27, 20));
        currentDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                currentDateChooserPropertyChange(evt);
            }
        });
        getContentPane().add(currentDateChooser);
        currentDateChooser.setBounds(700, 870, 220, 30);

        label13.setAlignment(java.awt.Label.CENTER);
        label13.setBackground(new java.awt.Color(0, 102, 0));
        label13.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label13.setForeground(new java.awt.Color(255, 255, 255));
        label13.setText("Product Name");
        getContentPane().add(label13);
        label13.setBounds(30, 660, 170, 30);

        category_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stimulants", "Depressants", "Hillacinogens", "Dissociatives", "Opioids", "Inhalants", "Cannabis" }));
        category_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_comboActionPerformed(evt);
            }
        });
        getContentPane().add(category_combo);
        category_combo.setBounds(230, 730, 220, 30);

        reset_button1.setBackground(new java.awt.Color(51, 102, 0));
        reset_button1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        reset_button1.setForeground(new java.awt.Color(204, 255, 204));
        reset_button1.setText("DEMO");
        reset_button1.setBorder(null);
        reset_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_button1ActionPerformed(evt);
            }
        });
        getContentPane().add(reset_button1);
        reset_button1.setBounds(490, 990, 150, 40);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0), new java.awt.Color(51, 204, 0), new java.awt.Color(51, 153, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 550, 980, 530);

        delete_btn.setBackground(new java.awt.Color(51, 102, 0));
        delete_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(204, 255, 204));
        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        delete_btn.setText("DELETE");
        delete_btn.setBorder(null);
        delete_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn);
        delete_btn.setBounds(1740, 490, 160, 40);

        update_btn.setBackground(new java.awt.Color(51, 102, 0));
        update_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(204, 255, 204));
        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        update_btn.setText("UPDATE");
        update_btn.setBorder(null);
        update_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update_btn);
        update_btn.setBounds(1580, 490, 150, 40);

        print_btn.setBackground(new java.awt.Color(51, 102, 0));
        print_btn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        print_btn.setForeground(new java.awt.Color(204, 255, 204));
        print_btn.setText("GENERATE REPORT");
        print_btn.setBorder(null);
        print_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });
        getContentPane().add(print_btn);
        print_btn.setBounds(1410, 490, 160, 40);

        label25.setAlignment(java.awt.Label.CENTER);
        label25.setBackground(new java.awt.Color(0, 102, 51));
        label25.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        label25.setForeground(new java.awt.Color(255, 255, 255));
        label25.setText("VIEW PRODUCT DETAILS");
        getContentPane().add(label25);
        label25.setBounds(1300, 90, 340, 60);

        viedetail_txt.setColumns(20);
        viedetail_txt.setRows(5);
        jScrollPane2.setViewportView(viedetail_txt);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1020, 200, 880, 260);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 153, 51), new java.awt.Color(51, 153, 0), new java.awt.Color(0, 153, 102), new java.awt.Color(0, 204, 51)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(980, 70, 940, 480);

        clear_button.setBackground(new java.awt.Color(51, 102, 0));
        clear_button.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        clear_button.setForeground(new java.awt.Color(204, 255, 204));
        clear_button.setText("CLEAR");
        clear_button.setBorder(null);
        clear_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(clear_button);
        clear_button.setBounds(820, 490, 140, 40);

        viewall_button.setBackground(new java.awt.Color(51, 102, 0));
        viewall_button.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        viewall_button.setForeground(new java.awt.Color(204, 255, 204));
        viewall_button.setText("VIEW ALL PRODUCTS");
        viewall_button.setBorder(null);
        viewall_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewall_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(viewall_button);
        viewall_button.setBounds(30, 490, 170, 40);

        search_exp_button.setBackground(new java.awt.Color(51, 102, 0));
        search_exp_button.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        search_exp_button.setForeground(new java.awt.Color(204, 255, 204));
        search_exp_button.setText("VIEW EXPIRED PRODUCTS");
        search_exp_button.setBorder(null);
        search_exp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_exp_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(search_exp_button);
        search_exp_button.setBounds(220, 490, 160, 40);

        jButton_search.setBackground(new java.awt.Color(51, 102, 0));
        jButton_search.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton_search.setForeground(new java.awt.Color(204, 255, 204));
        jButton_search.setText("SEARCH");
        jButton_search.setBorder(null);
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_search);
        jButton_search.setBounds(820, 170, 130, 30);
        getContentPane().add(textbox_search);
        textbox_search.setBounds(410, 170, 400, 30);

        view_button.setBackground(new java.awt.Color(51, 102, 0));
        view_button.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        view_button.setForeground(new java.awt.Color(204, 255, 204));
        view_button.setText("VIEW");
        view_button.setBorder(null);
        view_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(view_button);
        view_button.setBounds(660, 490, 150, 40);

        search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        search_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(search_table);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(30, 230, 930, 230);

        open_navi_button.setBackground(new java.awt.Color(0, 102, 0));
        open_navi_button.setForeground(new java.awt.Color(0, 102, 51));
        open_navi_button.setText("||||");
        open_navi_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        open_navi_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        open_navi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_navi_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(open_navi_button);
        open_navi_button.setBounds(10, 80, 30, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0), new java.awt.Color(102, 204, 0), new java.awt.Color(51, 153, 0)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 70, 980, 480);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1290, 70, 70, 260);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1630, 20, 290, 530);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 70, 330, 530);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 550, 330, 530);

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        // TODO add your handling code here:
    int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO RESET?", "RESET", JOptionPane.YES_NO_OPTION);    
        clearfields();
    }//GEN-LAST:event_reset_buttonActionPerformed

    public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
        if(date!=null){
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
        }
        return null;
    }
    
    private void clearfields(){
        addname_txt.setText(null);
        comboselect.setSelectedIndex(1);
        addspeci_txt.setText(null);
        adddose_txt.setText(null);
        java.util.Date date = null;
        ManuDateChooser.setDate(date);
        expiryDateChooser.setDate(date);
        currentDateChooser.setDate(date);
        addamount_txt.setText(null);
        jSpinner1.setValue(1);
    }
    
    private void clearfields1(){
        updatename_txt.setText(null);
        category2_combo.setSelectedIndex(1);
        updateamount_txt.setText(null);
        updatedose_txt.setText(null);
        java.util.Date date = null;
        upmanuDateChooser.setDate(date);
        upcurrentDateChooser.setDate(date);
        upexpiryDateChooser.setDate(date);
        updatespeciality_txt.setText(null);
    }
    
   
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
                       String name = addname_txt.getText();         
                       String speciality = addspeci_txt.getText();
                       Calendar cur = Calendar.getInstance();
                       Date sqldate = new Date((cur.getTime()).getTime());
      if(addname_txt.getText().isEmpty() || addspeci_txt.getText().isEmpty() || adddose_txt.getText().isEmpty() || ManuDateChooser.getDate() == null || addamount_txt.getText().isEmpty() || expiryDateChooser.getDate() == null || currentDateChooser.getDate() == null)
         JOptionPane.showMessageDialog(null,"FILL ALL FIELDS");
      else if((!speciality.matches("^[a-zA-Z]+$")) || (!name.matches("^[a-zA-Z]+$")))
        JOptionPane.showMessageDialog(null,"AVOID USING NUMBERS FOR NAME AND SPECIALITY FIELDS");
      else if(Integer.parseInt(addamount_txt.getText())<0){
          JOptionPane.showMessageDialog(null,"AMOUNT CANNOT BE A NEGATIVE VALUE");
      }
      else if(!sqldate.after(ManuDateChooser.getDate())){
          JOptionPane.showMessageDialog(null,"MANUFACTURE DATE CANNOT BE A FUTURE VALUE");
      }
      else if(Integer.parseInt(jSpinner1.getValue().toString())<=0){
          JOptionPane.showMessageDialog(null,"PLEASE ENTER A CORRECT QUANTITY");
      }
      else{
        try{
           String sql = "INSERT INTO product" + "(name,category,speciality,dosage,manufacture_date,expiry_date,mac_date,amount,quantity)" + "VALUES (?,?,?,?,?,?,?,?,?)";
           con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           pat = con.prepareStatement(sql);
           pat.setString(1,addname_txt.getText());
           pat.setString(2, (String) category_combo.getSelectedItem());
           pat.setString(3,addspeci_txt.getText());
           pat.setString(4,adddose_txt.getText());
           pat.setDate(5,convertUtilDateToSqlDate(ManuDateChooser.getDate())); 
           pat.setDate(6,convertUtilDateToSqlDate(expiryDateChooser.getDate()));
           pat.setDate(7,convertUtilDateToSqlDate(currentDateChooser.getDate()));
           pat.setString(8,addamount_txt.getText());
           pat.setString(9,jSpinner1.getValue().toString());
           pat.executeUpdate();
           JOptionPane.showMessageDialog(null,"PRODUCT ADDED SUCCESSFULLY");
           clearfields();
       }
       catch(UnsupportedOperationException | SQLException ex){
           JOptionPane.showMessageDialog(null,ex);
       }
      }
    }//GEN-LAST:event_add_buttonActionPerformed
    
    private void cancel_upd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_upd_btnActionPerformed
        // TODO add your handling code here:
        clearfields1();
    }//GEN-LAST:event_cancel_upd_btnActionPerformed

    
    private void update1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1_btnActionPerformed
                       String name = updatename_txt.getText();         
                       String speciality = updatespeciality_txt.getText(); 
                       Calendar cur = Calendar.getInstance();
                       Date sqldate = new Date((cur.getTime()).getTime());
      if(updatename_txt.getText().isEmpty() || updatespeciality_txt.getText().isEmpty() || updatedose_txt.getText().isEmpty() || upmanuDateChooser.getDate() == null || updateamount_txt.getText().isEmpty() || upexpiryDateChooser.getDate() == null || upcurrentDateChooser.getDate() == null)
         JOptionPane.showMessageDialog(null,"FILL ALL FIELDS");
      else if((!speciality.matches("^[a-zA-Z]+$")) || (!name.matches("^[a-zA-Z]+$")))
        JOptionPane.showMessageDialog(null,"AVOID USING INTEGERS FOR NAME AND SPECIALITY FIELDS");
      else if(Integer.parseInt(updateamount_txt.getText())<0){
          JOptionPane.showMessageDialog(null,"AMOUNT CANNOT BE A NEGATIVE VALUE");
      }
       else if(!sqldate.after(upmanuDateChooser.getDate())){
          JOptionPane.showMessageDialog(null,"MANUFACTURE DATE CANNOT BE A FUTURE VALUE");
      }
      else if(Integer.parseInt(jSpinner2.getValue().toString())<=0){
          JOptionPane.showMessageDialog(null,"PLEASE ENTER A CORRECT QUANTITY");
      }
      else{       
        int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO UPDATE THIS RECORD?", "UPDATE", JOptionPane.YES_NO_OPTION);
        if(op==0){
        try{
     
             int i = search_table.getSelectedRow();
        TableModel model = search_table.getModel();
        
           String sq4 = "UPDATE product SET name=?, category=?, speciality=?, dosage=?,manufacture_date=?,expiry_date=?,mac_date=?,amount=?,quantity=? WHERE pid=?";
           con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           pat = con.prepareStatement(sq4);
           pat.setString(1,updatename_txt.getText());
           pat.setString(2, (String) category2_combo.getSelectedItem());
           pat.setString(3,updatespeciality_txt.getText());
           pat.setString(4,updatedose_txt.getText());
           pat.setDate(5,convertUtilDateToSqlDate(upmanuDateChooser.getDate())); 
           pat.setDate(6,convertUtilDateToSqlDate(upexpiryDateChooser.getDate()));
           pat.setDate(7,convertUtilDateToSqlDate(upcurrentDateChooser.getDate()));
           pat.setString(8,updateamount_txt.getText());
           pat.setString(9,jSpinner2.getValue().toString());
           pat.setString(10,model.getValueAt(i, 0).toString());
           pat.executeUpdate();
           JOptionPane.showMessageDialog(null,"PRODUCT UPDATED SUCCESSFULLY");
           clearfields1();
       }
       catch(UnsupportedOperationException | SQLException ex){
           JOptionPane.showMessageDialog(null,ex);
       }        // TODO add your handling code here:
       }
     }
    }//GEN-LAST:event_update1_btnActionPerformed

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed
             int i = search_table.getSelectedRow();
             TableModel model = search_table.getModel();
        
            textbox_search.setText(model.getValueAt(i, 1).toString());
            
        try {
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost/HappySmile","root","");
           
           JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\ADMIN\\Desktop\\Aravin ITP\\Happy_Smile_Dental_Clinic\\Happy_Smile_Dental_Clinic\\src\\ProductForm\\productForm.jrxml");
           String query = "SELECT * FROM product ";
           String path = "C:\\Users\\ADMIN\\Desktop\\Aravin ITP\\Happy_Smile_Dental_Clinic\\Happy_Smile_Dental_Clinic\\src\\ProductForm\\productForm.jrxml";
//           JRDesignQuery updateQuery = new  JRDesignQuery();
//           
//           updateQuery.setText(query);
//           
//           jdesign.setQuery(updateQuery);
           
           HashMap parameter = new HashMap();
           parameter.put("IDP", textbox_search.getText());
           
           JasperReport jreport = JasperCompileManager.compileReport(path);
           
           JasperPrint jprint = JasperFillManager.fillReport(jreport, parameter, con);
           
           
           JasperViewer.viewReport(jprint,false);
           
           
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        textbox_search.setText(null);
    }//GEN-LAST:event_print_btnActionPerformed

    private void viewall_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewall_buttonActionPerformed
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql1 = "SELECT * FROM product";
            pat = con.prepareStatement(sql1);
            rs=pat.executeQuery();
            search_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_viewall_buttonActionPerformed

    private void search_exp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_exp_buttonActionPerformed
         try{
           String sql = "SELECT * FROM product WHERE expiry_date = ?";
           con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
           pat = con.prepareStatement(sql);
           Calendar cur = Calendar.getInstance();
           Date sqldate = new Date((cur.getTime()).getTime());
           pat.setDate(1, (java.sql.Date)sqldate);
           rs=pat.executeQuery();
            search_table.setModel(DbUtils.resultSetToTableModel(rs));
                 if(search_table.getModel().getRowCount()<=0)
                    JOptionPane.showMessageDialog(null,"There is no any expired products");
       }
       catch(UnsupportedOperationException | SQLException ex){
           JOptionPane.showMessageDialog(null,ex);
       }
    }//GEN-LAST:event_search_exp_buttonActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
           if(!textbox_search.getText().isEmpty()){
               Object sel1 = comboselect.getSelectedItem();
           
                String selitem = sel1.toString();
            
           if("ID".equals(selitem)){
                try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql2 = "SELECT * FROM product WHERE pid = ?";
            pat = con.prepareStatement(sql2);
            pat.setString(1,textbox_search.getText());
            rs=pat.executeQuery();
            search_table.setModel(DbUtils.resultSetToTableModel(rs));
                if(search_table.getModel().getRowCount()<=0)
                    JOptionPane.showMessageDialog(null,"The Id you have entered is NOT available");
                }
                 catch(HeadlessException | SQLException ex){
                     JOptionPane.showMessageDialog(null, ex);
                 }
           }
           else if("NAME".equals(selitem)){
                try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql2 = "SELECT * FROM product WHERE name LIKE '"+textbox_search.getText()+"%'";
            pat = con.prepareStatement(sql2);
            rs=pat.executeQuery();
            search_table.setModel(DbUtils.resultSetToTableModel(rs));
             if(search_table.getModel().getRowCount()<=0)
                    JOptionPane.showMessageDialog(null,"The Name you have entered is NOT available");
                }
                 catch(HeadlessException | SQLException ex){
                     JOptionPane.showMessageDialog(null, ex);
                 }
           }
            else{
                try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql1 = "SELECT * FROM product WHERE category = ?";
            pat = con.prepareStatement(sql1);
            pat.setString(1,textbox_search.getText());
            rs=pat.executeQuery();
            search_table.setModel(DbUtils.resultSetToTableModel(rs));
             if(search_table.getModel().getRowCount()<=0)
                    JOptionPane.showMessageDialog(null,"The category you have entered is NOT available");
                }
                 catch(HeadlessException | SQLException ex){
                     JOptionPane.showMessageDialog(null, ex);
                 }
           }
           }
           else
               JOptionPane.showMessageDialog(null,"PLEASE SPECIFY WHAT YOU NEED TO SEARCH");
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void updatedose_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedose_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatedose_txtActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) search_table.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
         if(!viedetail_txt.getText().isEmpty()){
        // TODO add your handling code here:
       int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE?", "DELETE", JOptionPane.YES_NO_OPTION);
        if(op==0){
        try{
            int i = search_table.getSelectedRow();
        TableModel model = search_table.getModel();
        
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql3 = "DELETE FROM product WHERE pid = ?";
            pat = con.prepareStatement(sql3);
            pat.setString(1, model.getValueAt(i, 0).toString());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "DELETED SUCCESSFULLY");
            
            DefaultTableModel model1= (DefaultTableModel) search_table.getModel();
            model1.setRowCount(0);
            viedetail_txt.setText(null);
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        }
         }
        else
              JOptionPane.showMessageDialog(null, "NOTHING SPECIFIED TO DELETE");
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
         if(!viedetail_txt.getText().isEmpty()){
        int i = search_table.getSelectedRow();
        TableModel model = search_table.getModel();
        
        updatename_txt.setText(model.getValueAt(i, 1).toString());
        updatedose_txt.setText(model.getValueAt(i, 4).toString());
        updatespeciality_txt.setText(model.getValueAt(i, 3).toString());
        category2_combo.addItem(model.getValueAt(i, 2).toString());
        updateamount_txt.setText(model.getValueAt(i, 8).toString());
        upmanuDateChooser.setDate((java.util.Date) model.getValueAt(i, 5));
        upcurrentDateChooser.setDate((java.util.Date) model.getValueAt(i, 6));
        upexpiryDateChooser.setDate((java.util.Date) model.getValueAt(i, 7));
        jSpinner2.setValue(model.getValueAt(i,9));
        viedetail_txt.setText(null);
       // jDateChooser4.setDate(convertUtilDateToSqlDate(model.getValueAt(i, 5)); 
         }
         else
             JOptionPane.showMessageDialog(null, "NOTHING SPECIFIED TO UPDATE");
    }//GEN-LAST:event_update_btnActionPerformed

    private void comboselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboselectActionPerformed

    private void ManuDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ManuDateChooserPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ManuDateChooserPropertyChange

    private void currentDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_currentDateChooserPropertyChange

    }//GEN-LAST:event_currentDateChooserPropertyChange

    private void view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_buttonActionPerformed
        if(!search_table.getSelectionModel().isSelectionEmpty()){
        // TODO add your handling code here:
        try{
        int i = search_table.getSelectedRow();
        TableModel model = search_table.getModel();
        
        viedetail_txt.setText("*******************************************PRODUCT DETAILS***************************************\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Product ID : " + model.getValueAt(i, 0).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Product Name : " + model.getValueAt(i, 1).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Category : " + model.getValueAt(i, 2).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Speciality : " + model.getValueAt(i, 3).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Dosage : " + model.getValueAt(i, 4).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Manufacture Date : "  + model.getValueAt(i, 5).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Expiry Date : " + model.getValueAt(i, 6).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Added Date : " + model.getValueAt(i, 7).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Amount : " + model.getValueAt(i, 8).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Availability : " + model.getValueAt(i, 9).toString()+"\n");
        }catch(Exception ex){
            
        }
        }
        else
             JOptionPane.showMessageDialog(null, "NOTHING SPECIFIED TO VIEW");
    }//GEN-LAST:event_view_buttonActionPerformed

    private void category_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_comboActionPerformed

    private void open_navi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_navi_buttonActionPerformed
        // TODO add your handling code here:
        navi_panel.setVisible(true);
        hide_navi_button.setVisible(true);
        go_home.setVisible(true);
        go_product.setVisible(true);
        go_order.setVisible(true);
        sign_out_btn.setVisible(true);
        go_billing.setVisible(true);
        open_navi_button.setVisible(false);
        search_table.setEnabled(false);
        search_table.setVisible(false);
        searchby_label.setVisible(false);
        label13.setVisible(false);
        label7.setVisible(false);
        label11.setVisible(false);
        label4.setVisible(false);
    }//GEN-LAST:event_open_navi_buttonActionPerformed

    private void hide_navi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hide_navi_buttonActionPerformed
        // TODO add your handling code here:
        navi_panel.setVisible(false);
        hide_navi_button.setVisible(false);
        go_home.setVisible(false);
        go_product.setVisible(false);
        go_order.setVisible(false);
        sign_out_btn.setVisible(false);
        go_billing.setVisible(false);
        open_navi_button.setVisible(true);       
        searchby_label.setVisible(true);
        search_table.setEnabled(true);
        search_table.setVisible(true);
        label13.setVisible(true);
        label7.setVisible(true);
        label11.setVisible(true);
        label4.setVisible(true);
    }//GEN-LAST:event_hide_navi_buttonActionPerformed

    private void sign_out_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_out_btnActionPerformed
        // TODO add your handling code here:
         int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO SIGN OUT?", "SIGN OUT", JOptionPane.YES_NO_OPTION);
        if(op==0){
        LoginForm l1 = new LoginForm();
        l1.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_sign_out_btnActionPerformed

    private void go_billingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_billingActionPerformed
        // TODO add your handling code here:
         int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "CHANGE TO BILLING PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
         BillingForm bl = new BillingForm();
        bl.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_go_billingActionPerformed

    private void go_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_orderActionPerformed
        // TODO add your handling code here:
         int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "CHANGE TO ORDER PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
        OrderForm ol = new OrderForm();
        ol.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_go_orderActionPerformed

    private void go_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_productActionPerformed
        // TODO add your handling code here:
         int op = JOptionPane.showConfirmDialog(null, "YOU ARE ALREADY IN PRODUCT PAGE. DO YOU WANT TO RESET THE PAGE?", "PAGE RESET", JOptionPane.YES_NO_OPTION);
        if(op==0){
        ProductForm pl = new ProductForm();
        pl.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_go_productActionPerformed

    private void go_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_homeActionPerformed
        // TODO add your handling code here:
         int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "CHANGE TO HOME PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
        PhamacistLogin pl = new PhamacistLogin();
        pl.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_go_homeActionPerformed

    private void updateamount_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateamount_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateamount_txtActionPerformed

    private void addname_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addname_txtKeyPressed

    }//GEN-LAST:event_addname_txtKeyPressed

    private void addname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addname_txtActionPerformed

    private void addamount_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addamount_txtKeyTyped
  char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Amount should be numeric value");

        }        // TODO add your handling code here:
    }//GEN-LAST:event_addamount_txtKeyTyped

    private void updateamount_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateamount_txtKeyTyped
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Amount should be numeric value");

        }         // TODO add your handling code here:
    }//GEN-LAST:event_updateamount_txtKeyTyped

    private void reset_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_button1ActionPerformed
        // TODO add your handling code here:
        Calendar cur = Calendar.getInstance();
        Date sqldate = new Date((cur.getTime()).getTime());
        addname_txt.setText("demopro");
        adddose_txt.setText("2 pac");
        addspeci_txt.setText("pain killer");
        category_combo.setSelectedIndex(2);
        ManuDateChooser.setDate(sqldate);
        expiryDateChooser.setDate(sqldate);
        currentDateChooser.setDate(sqldate);
        addamount_txt.setText("400");
        jSpinner1.setValue(3);
    }//GEN-LAST:event_reset_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProductForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ManuDateChooser;
    private java.awt.Label Quantity;
    private javax.swing.JButton add_button;
    private javax.swing.JTextField addamount_txt;
    private javax.swing.JTextField adddose_txt;
    private javax.swing.JTextField addname_txt;
    private javax.swing.JTextField addspeci_txt;
    private javax.swing.JButton cancel_upd_btn;
    private javax.swing.JComboBox<String> category2_combo;
    private javax.swing.JComboBox<String> category_combo;
    private javax.swing.JButton clear_button;
    private javax.swing.JComboBox<String> comboselect;
    private com.toedter.calendar.JDateChooser currentDateChooser;
    private javax.swing.JButton delete_btn;
    private com.toedter.calendar.JDateChooser expiryDateChooser;
    private javax.swing.JButton go_billing;
    private javax.swing.JButton go_home;
    private javax.swing.JButton go_order;
    private javax.swing.JButton go_product;
    private javax.swing.JButton hide_navi_button;
    private javax.swing.JButton jButton_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JPanel navi_panel;
    private javax.swing.JButton open_navi_button;
    private javax.swing.JButton print_btn;
    private javax.swing.JButton reset_button;
    private javax.swing.JButton reset_button1;
    private javax.swing.JButton search_exp_button;
    private javax.swing.JTable search_table;
    private java.awt.Label searchby_label;
    private javax.swing.JButton sign_out_btn;
    private javax.swing.JTextField textbox_search;
    private com.toedter.calendar.JDateChooser upcurrentDateChooser;
    private javax.swing.JButton update1_btn;
    private javax.swing.JButton update_btn;
    private javax.swing.JTextField updateamount_txt;
    private javax.swing.JTextField updatedose_txt;
    private javax.swing.JTextField updatename_txt;
    private javax.swing.JTextField updatespeciality_txt;
    private com.toedter.calendar.JDateChooser upexpiryDateChooser;
    private com.toedter.calendar.JDateChooser upmanuDateChooser;
    private javax.swing.JTextArea viedetail_txt;
    private javax.swing.JButton view_button;
    private javax.swing.JButton viewall_button;
    // End of variables declaration//GEN-END:variables

 
}
