package Employee;


import LogIn.LoginForm;
import Patient_History.PatientHistory;
import adminlogin.adminlogin;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public final class sign_form extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public sign_form() {
       initComponents();
         setSize(1920,1080);
       setLocation(0,0);
         setResizable(false);
       showtable();
       
       
       Border field_border = BorderFactory.createMatteBorder(1, 2, 1, 1, Color.BLACK);
        firstname.setBorder(field_border);
        jd.setBorder(field_border);
        address.setBorder(field_border);
        nic.setBorder(field_border);
        email.setBorder(field_border);
        salary.setBorder(field_border);
        jt.setBorder(field_border);
        salary.setBorder(field_border);
        jt.setBorder(field_border);
        age.setBorder(field_border);
       
        telephone.setBorder(field_border);
        attendance.setBorder(field_border);
        lastname.setBorder(field_border);
        id.setBorder(field_border);
        
        
        
        
        // Border button = BorderFactory.createMatteBorder(2, 5, 2, 2, Color.BLACK);
         
        
         
    }
      
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Address = new javax.swing.JPanel();
        email1 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jt = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Gender = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        attendance = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jd = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        reset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        search_b = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        search_by = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        logout = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Viewfield = new javax.swing.JTextArea();
        view1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Address.setForeground(new java.awt.Color(0, 102, 51));
        Address.setLayout(null);
        Address.add(email1);
        email1.setBounds(760, 380, 0, 0);

        add.setForeground(new java.awt.Color(0, 102, 51));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ad2.png"))); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        Address.add(add);
        add.setBounds(40, 960, 100, 40);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Id");
        Address.add(jLabel6);
        jLabel6.setBounds(50, 320, 30, 23);

        delete.setForeground(new java.awt.Color(0, 102, 51));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        Address.add(delete);
        delete.setBounds(190, 960, 110, 40);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        Address.add(id);
        id.setBounds(250, 310, 270, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setText("First Name :");
        jLabel16.setAlignmentX(0.5F);
        jLabel16.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel16.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel16);
        jLabel16.setBounds(50, 350, 91, 27);

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnameKeyTyped(evt);
            }
        });
        Address.add(firstname);
        firstname.setBounds(250, 350, 270, 27);

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel24.setText("Last Name :");
        jLabel24.setAlignmentX(0.5F);
        jLabel24.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel24.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel24.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel24);
        jLabel24.setBounds(50, 390, 91, 27);

        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastnameKeyTyped(evt);
            }
        });
        Address.add(lastname);
        lastname.setBounds(250, 390, 270, 27);

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setText("Address :");
        jLabel20.setAlignmentX(0.5F);
        jLabel20.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel20.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel20.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel20);
        jLabel20.setBounds(50, 520, 91, 27);

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        Address.add(address);
        address.setBounds(250, 530, 270, 90);

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel29.setText("NIC/Passport :");
        jLabel29.setAlignmentX(0.5F);
        jLabel29.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel29.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel29.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel29);
        jLabel29.setBounds(40, 710, 130, 27);

        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        Address.add(nic);
        nic.setBounds(250, 710, 270, 27);

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel25.setText("Job Title :");
        jLabel25.setAlignmentX(0.5F);
        jLabel25.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel25.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel25.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel25);
        jLabel25.setBounds(40, 750, 91, 27);

        jt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Title", "Doctor", "Admin", "Nurse", "Receptionist", "Other" }));
        jt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtActionPerformed(evt);
            }
        });
        Address.add(jt);
        jt.setBounds(250, 750, 270, 30);

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel30.setText("E-mail :");
        jLabel30.setAlignmentX(0.5F);
        jLabel30.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel30.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel30.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel30);
        jLabel30.setBounds(40, 670, 91, 27);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });
        Address.add(email);
        email.setBounds(250, 670, 270, 27);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Address.add(jButton1);
        jButton1.setBounds(1040, 850, 79, 25);

        Gender.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Gender.setText("Gender");
        Gender.setAlignmentX(0.5F);
        Gender.setMaximumSize(new java.awt.Dimension(100, 14));
        Gender.setMinimumSize(new java.awt.Dimension(100, 14));
        Gender.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(Gender);
        Gender.setBounds(50, 440, 91, 27);

        buttonGroup1.add(male);
        male.setText("Male");
        male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleMouseClicked(evt);
            }
        });
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        Address.add(male);
        male.setBounds(250, 440, 70, 25);

        buttonGroup1.add(female);
        female.setText("Female");
        female.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleMouseClicked(evt);
            }
        });
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        Address.add(female);
        female.setBounds(340, 440, 80, 25);

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setText("Salary :");
        jLabel18.setAlignmentX(0.5F);
        jLabel18.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel18.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel18.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel18);
        jLabel18.setBounds(40, 850, 91, 27);

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryKeyTyped(evt);
            }
        });
        Address.add(salary);
        salary.setBounds(250, 850, 270, 27);

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel27.setText("Attendance :");
        jLabel27.setAlignmentX(0.5F);
        jLabel27.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel27.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel27.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel27);
        jLabel27.setBounds(30, 900, 180, 27);

        attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceActionPerformed(evt);
            }
        });
        attendance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                attendanceKeyTyped(evt);
            }
        });
        Address.add(attendance);
        attendance.setBounds(250, 890, 270, 27);

        jLabel33.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel33.setText("Joined Date :");
        jLabel33.setAlignmentX(0.5F);
        jLabel33.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel33.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel33.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel33);
        jLabel33.setBounds(40, 800, 130, 27);

        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });
        telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telephoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telephoneKeyTyped(evt);
            }
        });
        Address.add(telephone);
        telephone.setBounds(250, 630, 270, 27);

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel26.setText("Telephone NO :");
        jLabel26.setAlignmentX(0.5F);
        jLabel26.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel26.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel26.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel26);
        jLabel26.setBounds(40, 630, 170, 27);

        view.setBackground(new java.awt.Color(0, 102, 102));
        view.setForeground(new java.awt.Color(0, 102, 51));
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        Address.add(view);
        view.setBounds(1790, 850, 90, 40);

        update.setForeground(new java.awt.Color(0, 102, 51));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        Address.add(update);
        update.setBounds(340, 960, 110, 40);
        Address.add(jd);
        jd.setBounds(250, 800, 270, 30);

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 102, 0));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setName(""); // NOI18N
        label3.setText("HAPPY SMILE DENTAL CLINIC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(533, 533, 533)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(784, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Address.add(jPanel2);
        jPanel2.setBounds(0, 0, 1920, 70);

        reset.setForeground(new java.awt.Color(0, 102, 51));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        Address.add(reset);
        reset.setBounds(500, 960, 100, 40);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(null);

        search_b.setText("Search");
        search_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bActionPerformed(evt);
            }
        });
        jPanel3.add(search_b);
        search_b.setBounds(500, 10, 90, 30);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel3.add(search);
        search.setBounds(200, 10, 270, 30);

        search_by.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id", "firstname" }));
        jPanel3.add(search_by);
        search_by.setBounds(120, 10, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Search By");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 10, 100, 22);

        Address.add(jPanel3);
        jPanel3.setBounds(180, 100, 640, 50);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        Address.add(jScrollPane2);
        jScrollPane2.setBounds(20, 150, 1910, 150);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        Address.add(logout);
        logout.setBounds(1770, 70, 140, 40);

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Address.add(jButton4);
        jButton4.setBounds(0, 70, 80, 30);

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel34.setText("Age");
        jLabel34.setAlignmentX(0.5F);
        jLabel34.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel34.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel34.setPreferredSize(new java.awt.Dimension(100, 14));
        Address.add(jLabel34);
        jLabel34.setBounds(50, 470, 91, 27);

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });
        Address.add(age);
        age.setBounds(250, 470, 270, 27);

        Viewfield.setColumns(20);
        Viewfield.setRows(5);
        jScrollPane1.setViewportView(Viewfield);

        Address.add(jScrollPane1);
        jScrollPane1.setBounds(636, 356, 1240, 480);

        view1.setBackground(new java.awt.Color(0, 102, 102));
        view1.setForeground(new java.awt.Color(0, 102, 51));
        view1.setText("View");
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });
        Address.add(view1);
        view1.setBounds(1780, 310, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        Address.add(jLabel1);
        jLabel1.setBounds(-10, 90, 650, 980);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        Address.add(jLabel2);
        jLabel2.setBounds(640, 90, 660, 980);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        Address.add(jLabel3);
        jLabel3.setBounds(1290, 90, 620, 980);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 1919, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1944, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(firstname.getText().isEmpty()||lastname.getText().isEmpty()||buttonGroup1.isSelected(null)||age.getText().isEmpty()||address.getText().isEmpty()||telephone.getText().isEmpty()
                ||email.getText().isEmpty()||nic.getText().isEmpty()||jd.getDate()==null||salary.getText().isEmpty()||attendance.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Fields cannot be Empty");
           
           }  
        
        
        if(id.getText().isEmpty()){
            
             JOptionPane.showMessageDialog(null, "Enter id to update... ");
        }       
        else{

        try{
            String sql = "UPDATE user SET firstname=?,lastname=?,Gender=?, age=?,address=?,telephone=?,email=?,nic=?,joindate=?,salary=?,attendance=? WHERE id=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            pst = con.prepareStatement(sql);
            pst.setString(12, id.getText());
            pst.setString(1,firstname.getText());
            pst.setString(2,lastname.getText());
            pst.setString(3,gender);
            pst.setString(4,age.getText());
            pst.setString(5,address.getText());
            pst.setString(6,telephone.getText());
            pst.setString(7,email.getText());
            pst.setString(8,nic.getText());
           SimpleDateFormat sdf1 = new SimpleDateFormat("yyy-MM-dd");
            String jD = sdf1.format(jd.getDate());
            pst.setString(9, jD);
            //pst.setString(9,jd.getDate().toString());
            pst.setString(10,salary.getText());
            pst.setString(11,attendance.getText());
         
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update successfully");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
          }
          showtable();
    }//GEN-LAST:event_updateActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        //showtable();
          try{
        int i = table.getSelectedRow();
        TableModel model = table.getModel();
        
        Viewfield.setText("*********************************EMPLOYEE DETAILS****************************************\n");
        Viewfield.setText(Viewfield.getText()+"First Name : " + model.getValueAt(i, 0).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"Last Name : " + model.getValueAt(i, 1).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"Gender : " + model.getValueAt(i, 2).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"Age : " + model.getValueAt(i, 3).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"Tele Phone : " + model.getValueAt(i, 4).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"E-mail : "  + model.getValueAt(i, 5).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"Nic : " + model.getValueAt(i, 6).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"Job-Title : " + model.getValueAt(i, 7).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"Join Date : " + model.getValueAt(i, 8).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"Salary : " + model.getValueAt(i, 9).toString()+"\n");
        Viewfield.setText(Viewfield.getText()+"Attendance : " + model.getValueAt(i, 10).toString()+"\n");
     
        
        }catch(Exception ex){
            
        }
           
    }//GEN-LAST:event_viewActionPerformed

    private void telephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneKeyTyped
        // allow only numbers
       char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Phone number should be numeric value");

        }

    }//GEN-LAST:event_telephoneKeyTyped

    private void telephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneKeyPressed

    private void attendanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attendanceKeyTyped
        // TODO add your handling code here:
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Attendance should be numeric value");

        }
    }//GEN-LAST:event_attendanceKeyTyped

    private void attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void femaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleMouseClicked
         gender = "female";
    }//GEN-LAST:event_femaleMouseClicked

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void maleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleMouseClicked
        gender = "male";
    }//GEN-LAST:event_maleMouseClicked

    private void jtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtActionPerformed

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if(id.getText().isEmpty()){
            
             JOptionPane.showMessageDialog(null, "Enter id to Delete.... ");
        }       
        else{
        
        int YesOrNo =  JOptionPane.showConfirmDialog(null,"do you want to Delete?","",JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0){
        try{
            String sql = "DELETE FROM user WHERE id = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1,id.getText());
 

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete successfully");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
           
        }
        
        }}
        showtable();
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       if(firstname.getText().isEmpty()||lastname.getText().isEmpty()||buttonGroup1.isSelected(null)||age.getText().isEmpty()||address.getText().isEmpty()||telephone.getText().isEmpty()||email.getText().isEmpty()||nic.getText().isEmpty()||jd.getDate()==null||salary.getText().isEmpty()||attendance.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Fields cannot be Empty.........");
             
               
               
           
           }
         //String Password = String.valueOf(password.getPassword());
        try{
            String sql = "INSERT INTO user"+"(firstname, lastname,Gender, age, address, telephone, email, nic, joindate, jobtitle, salary, attendance)"+
            "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1,firstname.getText());
            pst.setString(2,lastname.getText());
            pst.setString(3,gender);
            pst.setString(4, age.getText());
            pst.setString(5,address.getText());
            pst.setString(6,telephone.getText());
            pst.setString(7,email.getText());
            pst.setString(8,nic.getText());
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyy-MM-dd");
            String jD = sdf1.format(jd.getDate());
            pst.setString(9, jD);
            pst.setString(10,jt.getSelectedItem().toString());
            pst.setString(11,salary.getText());
           
            pst.setString(12,attendance.getText());
           // pst.setString(13,username.getText());
           // pst.setString(13,password.valueOf(password.getPassword()));
            //pst.setString(14, Password);
            
            
             //;
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insert successfully");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
         //showtable();
       // }
       
    }
         showtable();
    }//GEN-LAST:event_addActionPerformed

      public void clearFeild(){
         id.setText(null);
         firstname.setText(null);
         lastname.setText(null);
         age.setText(null);
         address.setText(null);
         telephone.setText(null);
         email.setText(null);
         nic.setText(null);
         jd.setDate(null);
         salary.setText(null);
         attendance.setText(null);
         //username.setText(null);
         //password.setText(null);
         
      }
      
   
        //create a unction to check if the entred username already exists in the database
       /* public boolean checkUsername(String username){
            PreparedStatement st;
            ResultSet rs;
            boolean username_exist = false;
            
            String query = "SELECT * FROM `user` WHERE `username` = ?";
            
        try {
              
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
             
             pst.setString(1, username);
             rs = pst.executeQuery();
             
             if(rs.next())
             {
                 username_exist = true;
                 JOptionPane.showMessageDialog(null, "This uername is already taken choose another one, ", "Username Failed", 2);
             }
            
        } catch (SQLException ex) {
            Logger.getLogger(sign_form.class.getName()).log(Level.SEVERE, null, ex);
        
            
            return username_exist;
        }
*/    
    
    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        clearFeild();
    }//GEN-LAST:event_resetActionPerformed

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
         int i = table.getSelectedRow();
       TableModel model = table.getModel();
      
       firstname.setText(model.getValueAt(i,1).toString());
       lastname.setText(model.getValueAt(i,2).toString());
       
       String gender = model.getValueAt(i,3).toString();
            if(gender.equals("male")){
             male.setSelected(true);
            }
            else{
            female.setSelected(true);
            }
         age.setText(model.getValueAt(i, 4).toString());
       String jd = model.getValueAt(i,9).toString();
        address.setText(model.getValueAt(i,5).toString());
        telephone.setText(model.getValueAt(i,6).toString());
        email.setText(model.getValueAt(i,7).toString());
        nic.setText(model.getValueAt(i,8).toString());
         
        String jobtitle = model.getValueAt(i, 10).toString();
         
        switch (jobtitle){
            case "Select Title":
                jt.setSelectedIndex(0);
                break;
         case "Doctor":
                jt.setSelectedIndex(1);
                break;
         case "Admin":
                jt.setSelectedIndex(2);
                break;
         case "Nurse":
                jt.setSelectedIndex(3);
                break;
         case "Receptionist":
                jt.setSelectedIndex(4);
                break;
          case "Other":
                jt.setSelectedIndex(5);
                break;
                
        }
        salary.setText(model.getValueAt(i,11).toString());
        attendance.setText(model.getValueAt(i,12).toString());
       // username.setText(model.getValueAt(i,13).toString());
        
    }//GEN-LAST:event_tableMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
         int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO SIGN OUT?", "SIGN OUT", JOptionPane.YES_NO_OPTION);
        if(op==0){
        LoginForm l2 = new LoginForm();
        l2.setVisible(true);
        this.setVisible(false);}   
    }//GEN-LAST:event_logoutActionPerformed

    private void salaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryKeyTyped
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Salary should be numeric value");

        }
    }//GEN-LAST:event_salaryKeyTyped

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:
        //  String PATTERN="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        //+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        //Pattern patt = Pattern.compile(PATTERN);
        //Matcher match = patt.matcher(email.getText());
       // if(!match.matches()){
       //     email1.setText("incorrect!");
       // }
       // else{
         //   email1.setText(null);
       // }
    }//GEN-LAST:event_emailKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        adminlogin obj = new adminlogin();
        obj.setVisible(true);
        dispose();
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        // TODO add your handling code here:
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Age  should be 18+ ");
        }
    }//GEN-LAST:event_ageKeyTyped

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
        char in = evt.getKeyChar();
        System.out.println(in);
        if(Character.isLetter(in)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "id should be numeric value");
        }
    }//GEN-LAST:event_idKeyTyped

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped

    // TODO add your handling code here:
         String PATTERN="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(email.getText());
        if(!match.matches()){
            email1.setText("incorrect!");
        }
        else{
            email1.setText(null);
        }
    }//GEN-LAST:event_emailKeyTyped

    private void firstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyTyped
        // TODO add your handling code here:
          char ch = evt.getKeyChar();
        System.out.println(ch);
        if(Character.isDigit(ch)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Please give alphabetic value");
        }
    }//GEN-LAST:event_firstnameKeyTyped

    private void lastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameKeyTyped
        // TODO add your handling code here:
          char ch = evt.getKeyChar();
        System.out.println(ch);
        if(Character.isDigit(ch)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Please give alphabetic value");
        }
    }//GEN-LAST:event_lastnameKeyTyped

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void search_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bActionPerformed
        Object sel1 = search_by.getSelectedItem();
        String selitem = sel1.toString();

        if("Id".equals(selitem)){
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
                String sql2 = "SELECT * FROM user WHERE id = ?";
                pst = con.prepareStatement(sql2);
                pst.setString(1,search.getText());
                rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                if(table.getModel().getRowCount()<=0)
                JOptionPane.showMessageDialog(null,"Please enter the correct ID");
            }
            catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        else if("firstname".equals(selitem)){
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
                String sql2 = "SELECT * FROM user WHERE firstname LIKE '"+search.getText()+"%'";
                pst = con.prepareStatement(sql2);
                rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                if(table.getModel().getRowCount()<=0)
                JOptionPane.showMessageDialog(null,"Please Enter the correct Name");
            }
            catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, ex);
            }

        }
    }//GEN-LAST:event_search_bActionPerformed

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        // TODO add your handling code here:
        showtable();
    }//GEN-LAST:event_view1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
         try {
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost/HappySmile","root","");
           
           JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\ADMIN\\Desktop\\Aravin ITP\\Happy_Smile_Dental_Clinic\\Happy_Smile_Dental_Clinic\\src\\Employee\\employee.jrxml");
           String query = "SELECT * FROM user ";
           String path = "C:\\Users\\ADMIN\\Desktop\\Aravin ITP\\Happy_Smile_Dental_Clinic\\Happy_Smile_Dental_Clinic\\src\\Employee\\employee.jrxml";
//           JRDesignQuery updateQuery = new  JRDesignQuery();
//           
//           updateQuery.setText(query);
//           
//           jdesign.setQuery(updateQuery);
           
           HashMap parameter = new HashMap();
           parameter.put("EDP", id.getText());
           
           JasperReport jreport = JasperCompileManager.compileReport(path);
           
           JasperPrint jprint = JasperFillManager.fillReport(jreport, parameter, con);
           
           
           JasperViewer.viewReport(jprint,false);
           
           
           
           
           
       } catch (SQLException ex) {
           Logger.getLogger(sign_form.class.getName()).log(Level.SEVERE, null, ex);
       } catch (JRException ex) {
           Logger.getLogger(sign_form.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(sign_form.class.getName()).log(Level.SEVERE, null, ex);
       } 

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void showtable(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/happysmile","root","");
            String sql = "SELECT * FROM user";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Address;
    private javax.swing.JLabel Gender;
    private javax.swing.JTextArea Viewfield;
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField attendance;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email1;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jd;
    private javax.swing.JComboBox jt;
    private java.awt.Label label3;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField nic;
    private javax.swing.JButton reset;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField search;
    private javax.swing.JButton search_b;
    private javax.swing.JComboBox search_by;
    private javax.swing.JTable table;
    private javax.swing.JTextField telephone;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    private javax.swing.JButton view1;
    // End of variables declaration//GEN-END:variables

private String gender="";
}
